import type { TemplateField } from "@/components/prontuario/DynamicFieldsRenderer";

export interface BuiltInProntuarioTemplate {
  key: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  fields: TemplateField[];
}

const f = (
  name: string, label: string, type: TemplateField["type"],
  opts?: { required?: boolean; placeholder?: string; options?: string }
): TemplateField => ({
  id: crypto.randomUUID(),
  name,
  label,
  type,
  required: opts?.required ?? false,
  placeholder: opts?.placeholder,
  options: opts?.options,
});

export const PRONTUARIO_TEMPLATES: BuiltInProntuarioTemplate[] = [
  {
    key: "geral",
    name: "Consulta Geral",
    description: "Prontuário padrão para clínica geral e atendimento ambulatorial",
    icon: "🏥",
    color: "bg-blue-500/10 text-blue-600 border-blue-500/20",
    fields: [],
  },
  {
    key: "cardiologia",
    name: "Cardiologia",
    description: "Campos específicos para consulta cardiológica",
    icon: "❤️",
    color: "bg-red-500/10 text-red-600 border-red-500/20",
    fields: [
      f("pa_sistolica", "PA Sistólica (mmHg)", "number", { placeholder: "120" }),
      f("pa_diastolica", "PA Diastólica (mmHg)", "number", { placeholder: "80" }),
      f("frequencia_cardiaca", "Frequência Cardíaca (bpm)", "number", { placeholder: "72" }),
      f("ritmo_cardiaco", "Ritmo Cardíaco", "select", { options: "Sinusal,Fibrilação Atrial,Flutter Atrial,Taquicardia,Bradicardia,Arritmia,Outro" }),
      f("sopro_cardiaco", "Sopro Cardíaco", "select", { options: "Ausente,Sistólico grau I,Sistólico grau II,Sistólico grau III,Diastólico,Contínuo" }),
      f("edema_mmii", "Edema MMII", "select", { options: "Ausente,+/4+,++/4+,+++/4+,++++/4+" }),
      f("dor_toracica", "Dor Torácica", "boolean"),
      f("dispneia", "Dispneia", "select", { options: "Ausente,Aos grandes esforços,Aos médios esforços,Aos pequenos esforços,Em repouso" }),
      f("ecg_resultado", "ECG - Resultado", "textarea", { placeholder: "Ritmo sinusal, FC 72bpm..." }),
      f("ecocardiograma", "Ecocardiograma", "textarea", { placeholder: "FE, dimensões, alterações valvares..." }),
      f("classe_funcional_nyha", "Classe Funcional (NYHA)", "select", { options: "I,II,III,IV" }),
      f("risco_cardiovascular", "Risco Cardiovascular", "select", { options: "Baixo,Intermediário,Alto,Muito Alto" }),
    ],
  },
  {
    key: "ortopedia",
    name: "Ortopedia",
    description: "Consulta ortopédica com avaliação musculoesquelética",
    icon: "🦴",
    color: "bg-orange-500/10 text-orange-600 border-orange-500/20",
    fields: [
      f("regiao_acometida", "Região Acometida", "text", { placeholder: "Ex: Joelho direito, Coluna lombar..." }),
      f("mecanismo_lesao", "Mecanismo da Lesão", "textarea", { placeholder: "Como ocorreu a lesão..." }),
      f("tempo_evolucao", "Tempo de Evolução", "text", { placeholder: "Ex: 3 meses, 2 semanas..." }),
      f("dor_eva", "Escala de Dor (EVA 0-10)", "number", { placeholder: "0" }),
      f("tipo_dor", "Tipo de Dor", "select", { options: "Aguda,Crônica,Nociceptiva,Neuropática,Mecânica,Inflamatória" }),
      f("amplitude_movimento", "Amplitude de Movimento", "select", { options: "Normal,Levemente reduzida,Moderadamente reduzida,Gravemente reduzida,Ausente" }),
      f("forca_muscular", "Força Muscular (Escala MRC)", "select", { options: "0 - Sem contração,1 - Contração sem movimento,2 - Movimento sem gravidade,3 - Vence gravidade,4 - Vence resistência parcial,5 - Normal" }),
      f("testes_especiais", "Testes Especiais", "textarea", { placeholder: "Lachman, gaveta anterior, Phalen, Tinel..." }),
      f("exames_imagem", "Exames de Imagem", "textarea", { placeholder: "RX, RNM, TC — laudos e achados..." }),
      f("classificacao_lesao", "Classificação da Lesão", "text", { placeholder: "Ex: Grau II, Tipo A..." }),
      f("conduta_ortopedica", "Conduta Ortopédica", "select", { options: "Conservador,Imobilização,Fisioterapia,Infiltração,Cirúrgico,Acompanhamento" }),
    ],
  },
  {
    key: "oncologia",
    name: "Oncologia",
    description: "Acompanhamento oncológico com estadiamento e protocolo",
    icon: "🎗️",
    color: "bg-purple-500/10 text-purple-600 border-purple-500/20",
    fields: [
      f("tipo_neoplasia", "Tipo de Neoplasia", "text", { required: true, placeholder: "Ex: Carcinoma de mama, Linfoma..." }),
      f("localizacao_primaria", "Localização Primária", "text", { placeholder: "Ex: Mama esquerda QSE..." }),
      f("data_diagnostico", "Data do Diagnóstico", "date"),
      f("histopatologico", "Resultado Histopatológico", "textarea", { placeholder: "Tipo histológico, grau, margens..." }),
      f("estadiamento_tnm", "Estadiamento TNM", "text", { placeholder: "Ex: T2N1M0" }),
      f("estadio_clinico", "Estádio Clínico", "select", { options: "I,IA,IB,II,IIA,IIB,III,IIIA,IIIB,IIIC,IV,IVA,IVB" }),
      f("biomarcadores", "Biomarcadores", "textarea", { placeholder: "RE, RP, HER2, Ki-67, PDL-1, BRCA..." }),
      f("protocolo_tratamento", "Protocolo de Tratamento", "textarea", { required: true, placeholder: "Quimioterapia, radioterapia, imunoterapia..." }),
      f("ciclo_atual", "Ciclo Atual", "text", { placeholder: "Ex: 3/6 ciclos AC-T" }),
      f("efeitos_adversos", "Efeitos Adversos", "textarea", { placeholder: "Náuseas, fadiga, neuropatia..." }),
      f("performance_status", "Performance Status (ECOG)", "select", { options: "0 - Assintomático,1 - Sintomático ambulatorial,2 - Acamado <50%,3 - Acamado >50%,4 - Acamado 100%" }),
      f("resposta_tratamento", "Resposta ao Tratamento", "select", { options: "Resposta completa,Resposta parcial,Doença estável,Progressão de doença,Não avaliável" }),
      f("proximos_passos", "Próximos Passos", "textarea", { placeholder: "Exames de reavaliação, próximo ciclo..." }),
    ],
  },
  {
    key: "pediatria",
    name: "Pediatria",
    description: "Consulta pediátrica com crescimento e desenvolvimento",
    icon: "👶",
    color: "bg-pink-500/10 text-pink-600 border-pink-500/20",
    fields: [
      f("peso_kg", "Peso (kg)", "number", { placeholder: "0.0" }),
      f("altura_cm", "Altura/Comprimento (cm)", "number", { placeholder: "0" }),
      f("perimetro_cefalico", "Perímetro Cefálico (cm)", "number", { placeholder: "0" }),
      f("imc_percentil", "IMC / Percentil", "text", { placeholder: "Ex: Percentil 50" }),
      f("curva_crescimento", "Curva de Crescimento", "select", { options: "Adequado para idade,Abaixo do esperado,Acima do esperado,Risco nutricional" }),
      f("desenvolvimento_npm", "Desenvolvimento Neuropsicomotor", "select", { options: "Adequado para idade,Atraso leve,Atraso moderado,Atraso importante" }),
      f("marcos_desenvolvimento", "Marcos do Desenvolvimento", "textarea", { placeholder: "Sustenta cabeça, senta, anda, fala..." }),
      f("alimentacao", "Alimentação", "textarea", { placeholder: "Aleitamento, introdução alimentar, dieta..." }),
      f("vacinacao", "Vacinação", "select", { options: "Em dia,Atrasada,Incompleta,Recusa vacinal" }),
      f("vacinas_pendentes", "Vacinas Pendentes", "text", { placeholder: "Ex: Reforço DTP, Hepatite A..." }),
      f("sono", "Padrão de Sono", "text", { placeholder: "Horas/noite, cochilos..." }),
    ],
  },
  {
    key: "ginecologia",
    name: "Ginecologia / Obstetrícia",
    description: "Consulta ginecológica e acompanhamento pré-natal",
    icon: "🩺",
    color: "bg-rose-500/10 text-rose-600 border-rose-500/20",
    fields: [
      f("dum", "DUM (Data Última Menstruação)", "date"),
      f("ciclo_menstrual", "Ciclo Menstrual", "text", { placeholder: "Ex: Regular, 28 dias" }),
      f("gestacoes", "Gestações (G/P/A)", "text", { placeholder: "Ex: G2P1A0" }),
      f("metodo_contraceptivo", "Método Contraceptivo", "select", { options: "Nenhum,Pílula oral,DIU cobre,DIU hormonal,Implante,Injetável,Preservativo,Ligadura,Vasectomia,Outro" }),
      f("ig_semanas", "Idade Gestacional (semanas)", "number", { placeholder: "Apenas se gestante" }),
      f("dpp", "DPP (Data Provável Parto)", "date"),
      f("altura_uterina", "Altura Uterina (cm)", "number"),
      f("bcf", "BCF (bpm)", "number"),
      f("movimentos_fetais", "Movimentos Fetais", "select", { options: "Presentes,Ausentes,Reduzidos,Não se aplica" }),
      f("exame_especular", "Exame Especular", "textarea", { placeholder: "Colo, secreções, lesões..." }),
      f("citologia_resultado", "Citologia Oncótica", "select", { options: "Normal,ASC-US,LSIL,HSIL,ASC-H,AGC,Carcinoma,Não realizada" }),
      f("mamografia_resultado", "Mamografia", "select", { options: "BI-RADS 0,BI-RADS 1,BI-RADS 2,BI-RADS 3,BI-RADS 4,BI-RADS 5,Não realizada" }),
    ],
  },
  {
    key: "dermatologia",
    name: "Dermatologia",
    description: "Avaliação dermatológica com descrição de lesões",
    icon: "🧴",
    color: "bg-amber-500/10 text-amber-600 border-amber-500/20",
    fields: [
      f("localizacao_lesao", "Localização da Lesão", "text", { placeholder: "Ex: Face, dorso, antebraço D..." }),
      f("tipo_lesao", "Tipo de Lesão", "select", { options: "Mácula,Pápula,Placa,Nódulo,Vesícula,Bolha,Pústula,Úlcera,Erosão,Crosta,Escama,Tumor" }),
      f("descricao_lesao", "Descrição da Lesão", "textarea", { required: true, placeholder: "Cor, forma, bordas, superfície, tamanho..." }),
      f("tempo_evolucao", "Tempo de Evolução", "text", { placeholder: "Ex: 2 semanas, 6 meses..." }),
      f("sintomas_associados", "Sintomas Associados", "textarea", { placeholder: "Prurido, dor, ardor, sangramento..." }),
      f("fototipo", "Fototipo (Fitzpatrick)", "select", { options: "I,II,III,IV,V,VI" }),
      f("dermatoscopia", "Dermatoscopia", "textarea", { placeholder: "Padrão, estruturas, cores..." }),
      f("hipotese_diagnostica", "Hipótese Diagnóstica", "text", { placeholder: "Ex: Dermatite atópica, Melanoma..." }),
      f("biopsia", "Biópsia", "select", { options: "Não indicada,Indicada,Realizada - aguardando resultado,Resultado disponível" }),
      f("tratamento_topico", "Tratamento Tópico", "textarea", { placeholder: "Cremes, pomadas, loções..." }),
      f("procedimento_realizado", "Procedimento Realizado", "select", { options: "Nenhum,Crioterapia,Eletrocauterização,Curetagem,Biópsia excisional,Biópsia incisional,Laser,Peeling,Preenchimento,Toxina botulínica" }),
    ],
  },
  {
    key: "neurologia",
    name: "Neurologia",
    description: "Consulta neurológica com exame neurológico",
    icon: "🧠",
    color: "bg-indigo-500/10 text-indigo-600 border-indigo-500/20",
    fields: [
      f("nivel_consciencia", "Nível de Consciência", "select", { options: "Alerta,Sonolento,Torporoso,Comatoso" }),
      f("glasgow", "Escala de Glasgow (3-15)", "number", { placeholder: "15" }),
      f("orientacao", "Orientação", "select", { options: "Orientado TEP,Desorientado tempo,Desorientado espaço,Desorientado pessoa,Desorientado total" }),
      f("linguagem", "Linguagem", "select", { options: "Normal,Disartria,Afasia motora,Afasia sensitiva,Afasia mista" }),
      f("forca_mmss", "Força MMSS (D/E)", "text", { placeholder: "Ex: 5/5 bilateral" }),
      f("forca_mmii", "Força MMII (D/E)", "text", { placeholder: "Ex: 5/5 bilateral" }),
      f("reflexos", "Reflexos", "textarea", { placeholder: "Patelar, aquileu, bicipital..." }),
      f("sensibilidade", "Sensibilidade", "select", { options: "Normal,Hipoestesia,Anestesia,Hiperestesia,Parestesia" }),
      f("coordenacao", "Coordenação", "select", { options: "Normal,Dismetria,Disdiadococinesia,Ataxia" }),
      f("marcha", "Marcha", "select", { options: "Normal,Atáxica,Espástica,Parkinsoniana,Ceifante,Escarvante,Antálgica" }),
      f("nervos_cranianos", "Nervos Cranianos", "textarea", { placeholder: "Pupilas, motricidade ocular, facial..." }),
      f("exames_complementares", "Exames Complementares", "textarea", { placeholder: "EEG, RNM encéfalo, TC crânio..." }),
    ],
  },
  {
    key: "psiquiatria",
    name: "Psiquiatria",
    description: "Avaliação psiquiátrica com exame do estado mental",
    icon: "🧩",
    color: "bg-teal-500/10 text-teal-600 border-teal-500/20",
    fields: [
      f("aparencia", "Aparência", "textarea", { placeholder: "Vestuário, higiene, postura..." }),
      f("consciencia", "Consciência", "select", { options: "Lúcido,Obnubilado,Confuso,Torporoso" }),
      f("orientacao_psq", "Orientação", "select", { options: "Preservada,Parcialmente comprometida,Comprometida" }),
      f("humor", "Humor", "select", { options: "Eutímico,Deprimido,Eufórico,Irritável,Ansioso,Disfórico,Lábil" }),
      f("afeto", "Afeto", "select", { options: "Congruente,Incongruente,Embotado,Restrito,Expansivo" }),
      f("pensamento_curso", "Pensamento — Curso", "select", { options: "Normal,Acelerado,Lentificado,Tangencial,Circunstancial,Fuga de ideias,Bloqueio" }),
      f("pensamento_conteudo", "Pensamento — Conteúdo", "textarea", { placeholder: "Delírios, ideias obsessivas, suicidas..." }),
      f("percepcao", "Percepção", "select", { options: "Normal,Alucinações auditivas,Alucinações visuais,Ilusões,Despersonalização" }),
      f("risco_suicida", "Risco Suicida", "select", { required: true, options: "Ausente,Baixo,Moderado,Alto,Iminente" }),
      f("sono_psq", "Sono", "select", { options: "Normal,Insônia inicial,Insônia terminal,Hipersonia,Sono fragmentado" }),
      f("apetite_psq", "Apetite", "select", { options: "Normal,Aumentado,Diminuído,Ausente" }),
      f("medicacoes_psiquiatricas", "Medicações Psiquiátricas em Uso", "textarea", { placeholder: "Princípio ativo, dose, frequência..." }),
      f("escala_ham_d", "HAM-D (Depressão)", "number", { placeholder: "Score" }),
    ],
  },
  {
    key: "oftalmologia",
    name: "Oftalmologia",
    description: "Consulta oftalmológica com acuidade e fundoscopia",
    icon: "👁️",
    color: "bg-cyan-500/10 text-cyan-600 border-cyan-500/20",
    fields: [
      f("acuidade_od", "Acuidade Visual OD", "text", { placeholder: "Ex: 20/20" }),
      f("acuidade_oe", "Acuidade Visual OE", "text", { placeholder: "Ex: 20/40" }),
      f("acuidade_corrigida_od", "AV Corrigida OD", "text", { placeholder: "Ex: 20/20 com -2.00" }),
      f("acuidade_corrigida_oe", "AV Corrigida OE", "text", { placeholder: "Ex: 20/20 com -1.75" }),
      f("pressao_intraocular_od", "PIO OD (mmHg)", "number", { placeholder: "14" }),
      f("pressao_intraocular_oe", "PIO OE (mmHg)", "number", { placeholder: "14" }),
      f("biomicroscopia", "Biomicroscopia", "textarea", { placeholder: "Córnea, câmara anterior, cristalino..." }),
      f("fundoscopia_od", "Fundoscopia OD", "textarea", { placeholder: "Papila, mácula, vasos, retina..." }),
      f("fundoscopia_oe", "Fundoscopia OE", "textarea", { placeholder: "Papila, mácula, vasos, retina..." }),
      f("refracao_od", "Refração OD", "text", { placeholder: "Ex: -2.00 -0.50 x 180" }),
      f("refracao_oe", "Refração OE", "text", { placeholder: "Ex: -1.75 -0.75 x 175" }),
    ],
  },
  {
    key: "endocrinologia",
    name: "Endocrinologia",
    description: "Consulta endocrinológica com perfil metabólico",
    icon: "⚗️",
    color: "bg-emerald-500/10 text-emerald-600 border-emerald-500/20",
    fields: [
      f("peso_kg", "Peso (kg)", "number", { placeholder: "0.0" }),
      f("altura_cm", "Altura (cm)", "number", { placeholder: "0" }),
      f("imc", "IMC", "number", { placeholder: "0.0" }),
      f("circunferencia_abdominal", "Circunferência Abdominal (cm)", "number"),
      f("glicemia_jejum", "Glicemia de Jejum (mg/dL)", "number"),
      f("hba1c", "Hemoglobina Glicada (%)", "number", { placeholder: "0.0" }),
      f("tsh", "TSH (mUI/L)", "number"),
      f("t4_livre", "T4 Livre (ng/dL)", "number"),
      f("colesterol_total", "Colesterol Total", "number"),
      f("ldl", "LDL", "number"),
      f("hdl", "HDL", "number"),
      f("triglicerides", "Triglicerídeos", "number"),
      f("medicacoes_endo", "Medicações Endócrinas", "textarea", { placeholder: "Insulina, metformina, levotiroxina..." }),
      f("meta_glicemica", "Meta Glicêmica", "text", { placeholder: "Ex: HbA1c < 7%" }),
    ],
  },
  {
    key: "odontologia",
    name: "Odontologia",
    description: "Prontuário odontológico completo com anamnese específica",
    icon: "🦷",
    color: "bg-sky-500/10 text-sky-600 border-sky-500/20",
    fields: [
      // Queixa Principal
      f("queixa_principal_odonto", "Queixa Principal", "textarea", { required: true, placeholder: "Motivo da consulta odontológica..." }),
      
      // Anamnese Odontológica (mínimo 10 perguntas)
      f("ultima_visita_dentista", "Última visita ao dentista", "text", { placeholder: "Ex: 6 meses, 1 ano, nunca..." }),
      f("frequencia_escovacao", "Frequência de escovação", "select", { options: "1x ao dia,2x ao dia,3x ao dia,Após cada refeição,Irregular" }),
      f("uso_fio_dental", "Uso de fio dental", "select", { options: "Diariamente,Algumas vezes por semana,Raramente,Nunca" }),
      f("uso_enxaguante", "Uso de enxaguante bucal", "select", { options: "Diariamente,Algumas vezes por semana,Raramente,Nunca" }),
      f("sangramento_gengival", "Sangramento gengival", "select", { options: "Nunca,Às vezes ao escovar,Frequentemente,Espontâneo" }),
      f("sensibilidade_dentaria", "Sensibilidade dentária", "select", { options: "Ausente,Ao frio,Ao calor,Ao doce,Múltiplos estímulos" }),
      f("bruxismo", "Bruxismo (ranger/apertar dentes)", "select", { options: "Não,Sim - diurno,Sim - noturno,Sim - ambos,Não sabe" }),
      f("dor_atm", "Dor ou estalido na ATM", "select", { options: "Não,Dor ao mastigar,Estalido,Travamento,Dor + estalido" }),
      f("habitos_nocivos", "Hábitos nocivos", "textarea", { placeholder: "Roer unhas, morder objetos, fumar, mascar chicletes..." }),
      f("historico_tratamento_odonto", "Histórico de tratamentos odontológicos", "textarea", { placeholder: "Extrações, canais, implantes, ortodontia..." }),
      f("alergia_anestesico", "Alergia a anestésico local", "select", { options: "Não,Sim,Não sabe" }),
      f("alergia_latex", "Alergia a látex", "select", { options: "Não,Sim,Não sabe" }),
      f("medicamentos_uso", "Medicamentos em uso", "textarea", { placeholder: "Anticoagulantes, bifosfonatos, imunossupressores..." }),
      f("doencas_sistemicas", "Doenças sistêmicas relevantes", "textarea", { placeholder: "Diabetes, hipertensão, cardiopatias, hepatite..." }),
      
      // Exame Clínico
      f("exame_extraoral", "Exame Extraoral", "textarea", { placeholder: "Face, linfonodos, ATM, músculos mastigatórios..." }),
      f("exame_intraoral_tecidos", "Exame Intraoral - Tecidos Moles", "textarea", { placeholder: "Mucosa, língua, palato, assoalho, gengiva..." }),
      f("exame_intraoral_dentes", "Exame Intraoral - Dentes", "textarea", { required: true, placeholder: "Condição dos dentes, cáries, restaurações, ausências..." }),
      f("indice_placa", "Índice de Placa Visível", "select", { options: "Bom (<20%),Regular (20-50%),Ruim (>50%)" }),
      f("indice_sangramento", "Índice de Sangramento Gengival", "select", { options: "Ausente,Leve (<10%),Moderado (10-30%),Severo (>30%)" }),
      
      // Exame Radiográfico
      f("exame_radiografico", "Exame Radiográfico", "textarea", { placeholder: "Panorâmica, periapicais, interproximais - achados..." }),
      f("tipo_radiografia", "Tipo de Radiografia", "select", { options: "Não realizada,Panorâmica,Periapical,Interproximal,Tomografia,Múltiplas" }),
      
      // Classificação de Risco (CAMBRA)
      f("risco_carie", "Classificação de Risco de Cárie (CAMBRA)", "select", { required: true, options: "Baixo,Moderado,Alto,Extremo" }),
      f("fatores_risco_carie", "Fatores de Risco Identificados", "textarea", { placeholder: "Dieta cariogênica, xerostomia, biofilme, etc..." }),
      f("fatores_protecao", "Fatores de Proteção", "textarea", { placeholder: "Flúor, selantes, boa higiene, saliva normal..." }),
      
      // Diagnóstico
      f("diagnostico_odonto", "Diagnóstico Odontológico", "textarea", { required: true, placeholder: "Cárie, doença periodontal, má oclusão, etc..." }),
      f("cid_odonto", "CID-10 Odontológico", "text", { placeholder: "K02, K05, K08..." }),
      
      // Plano de Tratamento
      f("plano_tratamento_odonto", "Plano de Tratamento", "textarea", { required: true, placeholder: "Procedimentos planejados por dente/região..." }),
      f("urgencia_tratamento", "Urgência do Tratamento", "select", { options: "Eletivo,Necessário em breve,Urgente,Emergência" }),
      f("numero_sessoes", "Número Estimado de Sessões", "number", { placeholder: "0" }),
      f("orcamento_aprovado", "Orçamento Aprovado", "boolean"),
      
      // Procedimentos Realizados
      f("procedimentos_realizados", "Procedimentos Realizados Nesta Sessão", "textarea", { placeholder: "Profilaxia, restauração dente X, etc..." }),
      f("anestesia_utilizada", "Anestesia Utilizada", "text", { placeholder: "Tipo, quantidade, lote..." }),
      f("materiais_utilizados", "Materiais Utilizados", "textarea", { placeholder: "Resina, amálgama, cimento, etc..." }),
      
      // Orientações
      f("orientacoes_paciente", "Orientações ao Paciente", "textarea", { placeholder: "Cuidados pós-procedimento, higiene, retorno..." }),
      f("retorno_previsto", "Retorno Previsto", "text", { placeholder: "Ex: 7 dias, 1 mês, 6 meses..." }),
    ],
  },
];
