project_id = "pijjuhtyxcidqceukogv"

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.send-custom-auth-email]
verify_jwt = false

[functions.invite-team-member]
verify_jwt = false

[functions.send-support-ticket-email]
verify_jwt = false

[functions.update-password]
verify_jwt = false

[functions.jwt-probe]
verify_jwt = true

[functions.public-booking]
verify_jwt = false

[functions.run-campaign]
verify_jwt = true