// Auto-generated from gcp/migrations/ — used by the schema-audit endpoint.
// patient_consents uses the complete version from 11_consent_documents (not 02_patients).

export const EXPECTED_SCHEMA: Record<string, string[]> = {
  'clinic_rooms': ['id', 'tenant_id', 'unit_id', 'name', 'room_type', 'capacity', 'floor', 'equipment', 'is_active', 'created_at', 'updated_at'],
  'clinic_units': ['id', 'tenant_id', 'name', 'phone', 'address_street', 'address_city', 'address_state', 'address_zip', 'cnes_code', 'is_active', 'created_at', 'updated_at'],
  'email_verification_codes': ['id', 'user_id', 'email', 'code', 'attempts', 'verified', 'expires_at', 'created_at'],
  'override_audit_log': ['id', 'tenant_id', 'override_type', 'override_id', 'action', 'old_value', 'new_value', 'changed_by', 'changed_at'],
  'permission_overrides': ['id', 'tenant_id', 'user_id', 'resource', 'can_view', 'can_create', 'can_edit', 'can_delete', 'created_at'],
  'professional_working_hours': ['id', 'tenant_id', 'professional_id', 'day_of_week', 'start_time', 'end_time', 'is_active', 'created_at'],
  'profiles': ['id', 'user_id', 'tenant_id', 'full_name', 'email', 'phone', 'avatar_url', 'professional_type', 'council_type', 'council_number', 'council_state', 'specialty', 'is_active', 'created_at', 'updated_at'],
  'role_templates': ['id', 'tenant_id', 'name', 'professional_type', 'permissions', 'is_system', 'created_at', 'updated_at'],
  'room_occupancies': ['id', 'tenant_id', 'room_id', 'appointment_id', 'professional_id', 'client_name', 'status', 'started_at', 'ended_at', 'notes'],
  'rooms': ['id', 'tenant_id', 'name', 'description', 'is_active', 'created_at', 'updated_at'],
  'rpc_rate_limits': ['user_id', 'rpc_name', 'window_start', 'call_count'],
  'schedule_blocks': ['id', 'tenant_id', 'professional_id', 'start_at', 'end_at', 'reason', 'created_at'],
  'specialties': ['id', 'tenant_id', 'name', 'description', 'is_active', 'created_at', 'updated_at'],
  'subscriptions': ['id', 'tenant_id', 'stripe_customer_id', 'stripe_subscription_id', 'asaas_customer_id', 'asaas_subscription_id', 'status', 'plan', 'trial_start', 'trial_end', 'current_period_start', 'current_period_end', 'team_limit', 'created_at', 'updated_at'],
  'tenant_feature_overrides': ['id', 'tenant_id', 'feature_key', 'is_enabled', 'reason', 'enabled_by', 'expires_at', 'created_at', 'updated_at'],
  'tenant_limit_overrides': ['id', 'tenant_id', 'limit_key', 'custom_value', 'reason', 'enabled_by', 'expires_at', 'created_at', 'updated_at'],
  'tenant_payment_gateways': ['id', 'tenant_id', 'provider', 'api_key_encrypted', 'webhook_secret_encrypted', 'environment', 'is_active', 'is_split_enabled', 'split_fee_payer', 'metadata', 'last_validated_at', 'validation_status', 'created_at', 'updated_at'],
  'tenant_sequences': ['tenant_id', 'attendance_seq', 'updated_at'],
  'tenant_theme_settings': ['id', 'tenant_id', 'primary_h', 'primary_s', 'primary_l', 'accent_h', 'accent_s', 'accent_l', 'preset_name', 'logo_url', 'logo_dark_url', 'favicon_url', 'border_radius', 'font_family', 'created_at', 'updated_at'],
  'tenants': ['id', 'name', 'phone', 'email', 'address', 'cnpj', 'cpf', 'logo_url', 'website', 'whatsapp_api_url', 'whatsapp_api_key', 'whatsapp_instance', 'whatsapp_phone_number_id', 'whatsapp_access_token', 'whatsapp_business_account_id', 'enabled_modules', 'simple_mode', 'reply_to_email', 'created_at', 'updated_at', 'nfeio_active', 'nfeio_api_key', 'nfeio_auto_emit', 'nfeio_certificate_expires', 'nfeio_company_id', 'nfeio_default_service_code', 'billing_cpf_cnpj', 'cashback_enabled', 'default_commission_percent', 'email_reply_to', 'gamification_enabled', 'online_booking_enabled', 'patient_booking_enabled', 'patient_payment_enabled', 'points_enabled', 'retention_years', 'rnds_enabled', 'show_clinic_average_to_staff', 'smart_confirmation_enabled', 'sms_provider', 'stone_api_key', 'autonomous_config'],
  'user_roles': ['id', 'user_id', 'tenant_id', 'role', 'created_at'],
  'client_marketing_preferences': ['id', 'tenant_id', 'patient_id', 'email_opt_in', 'sms_opt_in', 'whatsapp_opt_in', 'push_opt_in', 'updated_at', 'created_at'],
  'client_package_ledger': ['id', 'package_id', 'tenant_id', 'appointment_id', 'action', 'quantity', 'created_at'],
  'client_packages': ['id', 'tenant_id', 'patient_id', 'name', 'total_sessions', 'used_sessions', 'price', 'status', 'expires_at', 'created_at', 'updated_at'],
  // 'clients' removed — legacy alias for 'patients' (which already exists in DB)
  'insurance_plans': ['id', 'tenant_id', 'name', 'ans_code', 'contact_phone', 'is_active', 'created_at', 'updated_at'],
  'patient_access_attempts': ['id', 'identifier_hash', 'success', 'ip_hint', 'created_at'],
  'patient_achievements': ['id', 'tenant_id', 'patient_id', 'achievement_type', 'metadata', 'created_at'],
  'patient_activity_log': ['id', 'patient_user_id', 'event_type', 'event_description', 'metadata', 'ip_hint', 'user_agent', 'created_at'],
  'patient_calls': ['id', 'tenant_id', 'patient_id', 'appointment_id', 'triage_id', 'room_id', 'room_name', 'professional_id', 'professional_name', 'status', 'priority', 'priority_label', 'call_number', 'times_called', 'first_called_at', 'last_called_at', 'checked_in_at', 'started_service_at', 'completed_at', 'created_at', 'updated_at'],
  // Complete version from 11_consent_documents (supersedes 02_patients)
  'patient_consents': ['id', 'tenant_id', 'patient_id', 'template_id', 'patient_user_id', 'title', 'content', 'status', 'signed_at', 'signature_method', 'signature_url', 'manual_signature_path', 'facial_photo_path', 'photo_url', 'sealed_pdf_path', 'sealed_pdf_url', 'sealed_pdf_hash', 'sealed_at', 'template_snapshot_html', 'ip_address', 'user_agent', 'consent_hash', 'document_hash', 'created_at', 'updated_at'],
  'patient_deletion_requests': ['id', 'patient_id', 'user_id', 'reason', 'status', 'requested_at', 'scheduled_for', 'cancelled_at', 'completed_at', 'tenant_id'],
  'patient_dependents': ['id', 'tenant_id', 'guardian_patient_id', 'dependent_patient_id', 'relationship', 'created_at'],
  'patient_invoices': ['id', 'tenant_id', 'patient_id', 'amount', 'status', 'due_date', 'paid_at', 'description', 'external_payment_url', 'created_at', 'updated_at'],
  'patient_messages': ['id', 'tenant_id', 'patient_id', 'professional_id', 'direction', 'content', 'read', 'read_at', 'created_at'],
  'patient_notification_preferences': ['id', 'client_id', 'tenant_id', 'email_enabled', 'sms_enabled', 'whatsapp_enabled', 'push_enabled', 'opt_out_types', 'created_at', 'updated_at'],
  'patient_notifications': ['id', 'tenant_id', 'patient_id', 'title', 'message', 'type', 'read', 'read_at', 'metadata', 'created_at'],
  'patient_onboarding': ['id', 'patient_user_id', 'tour_completed', 'tour_completed_at', 'tour_skipped', 'first_login_at', 'last_login_at', 'login_count', 'created_at'],
  'patient_packages': ['id', 'tenant_id', 'patient_id', 'name', 'total_sessions', 'used_sessions', 'price', 'status', 'expires_at', 'created_at', 'updated_at'],
  'patient_payments': ['id', 'tenant_id', 'patient_id', 'invoice_id', 'amount', 'payment_method', 'external_id', 'status', 'created_at'],
  'patient_profiles': ['id', 'user_id', 'patient_id', 'tenant_id', 'full_name', 'email', 'phone', 'avatar_url', 'access_code', 'status', 'created_at', 'updated_at'],
  'patient_proms': ['id', 'tenant_id', 'patient_id', 'questionnaire_type', 'responses', 'score', 'created_at'],
  'patient_uploaded_exams': ['id', 'tenant_id', 'patient_id', 'user_id', 'file_name', 'file_path', 'file_size', 'mime_type', 'exam_name', 'exam_date', 'notes', 'status', 'reviewed_by', 'reviewed_at', 'created_at', 'updated_at'],
  'patient_vaccinations': ['id', 'tenant_id', 'patient_id', 'vaccine_name', 'dose', 'administered_at', 'lot_number', 'manufacturer', 'notes', 'created_at'],
  'patients': ['id', 'tenant_id', 'name', 'phone', 'email', 'cpf', 'rg', 'birth_date', 'gender', 'address', 'city', 'state', 'zip_code', 'notes', 'blood_type', 'allergies', 'chronic_conditions', 'emergency_contact_name', 'emergency_contact_phone', 'marketing_opt_out', 'photo_url', 'access_code', 'created_at', 'updated_at', 'date_of_birth', 'marital_status', 'street', 'street_number', 'complement', 'neighborhood', 'insurance_plan_id', 'insurance_card_number'],
  'pre_consultation_forms': ['id', 'tenant_id', 'service_id', 'name', 'description', 'fields', 'is_active', 'created_at', 'updated_at'],
  'pre_consultation_responses': ['id', 'tenant_id', 'appointment_id', 'form_id', 'patient_id', 'responses', 'submitted_at'],
  'return_confirmation_tokens': ['id', 'tenant_id', 'return_id', 'token', 'expires_at', 'used_at', 'action', 'created_at'],
  'return_reminders': ['id', 'tenant_id', 'medical_record_id', 'appointment_id', 'client_id', 'professional_id', 'service_id', 'return_days', 'return_date', 'reason', 'status', 'scheduled_appointment_id', 'notify_patient', 'notify_days_before', 'last_notification_at', 'notification_count', 'preferred_contact', 'created_by', 'created_at', 'updated_at'],
  'appointment_cashback_earnings': ['id', 'tenant_id', 'appointment_id', 'patient_id', 'amount', 'percentage', 'status', 'created_at', 'client_id', 'earned_amount', 'earned_at'],
  'appointment_completion_summaries': ['id', 'tenant_id', 'appointment_id', 'professional_name', 'service_name', 'service_profit', 'product_sales', 'product_profit_total', 'total_profit', 'created_at'],
  'appointment_package_consumptions': ['id', 'tenant_id', 'appointment_id', 'package_id', 'sessions_used', 'created_at', 'consumed_at'],
  'appointment_ratings': ['id', 'tenant_id', 'appointment_id', 'patient_user_id', 'rating', 'comment', 'created_at'],
  'appointments': ['id', 'tenant_id', 'patient_id', 'procedure_id', 'professional_id', 'specialty_id', 'insurance_plan_id', 'room_id', 'scheduled_at', 'duration_minutes', 'status', 'price', 'commission_amount', 'consultation_type', 'insurance_authorization', 'cid_code', 'notes', 'telemedicine', 'telemedicine_url', 'created_at', 'updated_at', 'booked_by_id', 'client_id', 'confirmation_sent_4h', 'confirmed_at', 'created_via', 'service_id', 'source', 'telemedicine_token', 'unit_id'],
  'waitlist_notifications': ['id', 'tenant_id', 'waitlist_id', 'patient_id', 'appointment_date', 'service_id', 'professional_id', 'period', 'status', 'sent_at', 'created_at'],
  'waitlist': ['id', 'tenant_id', 'patient_id', 'procedure_id', 'professional_id', 'preferred_dates', 'priority', 'notes', 'status', 'notified_at', 'created_at', 'updated_at', 'client_id', 'expires_at', 'preferred_periods', 'reason', 'scheduled_at', 'service_id', 'specialty_id'],
  'archived_clinical_data': ['id', 'tenant_id', 'client_id', 'client_name', 'client_cpf', 'client_cns', 'client_birth_date', 'medical_records', 'prescriptions', 'triages', 'evolutions', 'attachments', 'last_appointment_date', 'retention_expired_at', 'archived_at', 'archived_by', 'export_pdf_url', 'export_xml_url', 'export_generated_at', 'data_hash', 'can_be_deleted_after', 'created_at'],
  'clinical_evolutions': ['id', 'tenant_id', 'patient_id', 'professional_id', 'appointment_id', 'medical_record_id', 'evolution_date', 'evolution_type', 'subjective', 'objective', 'assessment', 'plan', 'cid_code', 'vital_signs', 'digital_hash', 'signed_at', 'signed_by_name', 'signed_by_crm', 'notes', 'created_at', 'updated_at', 'server_timestamp', 'signed_by_uf'],
  'dental_prescriptions': ['id', 'tenant_id', 'patient_id', 'professional_id', 'periogram_id', 'odontogram_id', 'prescription_date', 'diagnosis', 'medications', 'instructions', 'signed_at', 'signed_by_name', 'signed_by_cro', 'created_at', 'updated_at'],
  'exam_results': ['id', 'tenant_id', 'patient_id', 'professional_id', 'exam_type', 'exam_date', 'results', 'file_url', 'notes', 'status', 'created_at', 'updated_at', 'exam_category', 'performed_by', 'result_data'],
  'medical_certificates': ['id', 'tenant_id', 'patient_id', 'professional_id', 'certificate_type', 'content', 'days_off', 'start_date', 'cid_code', 'is_signed', 'signed_at', 'signature_hash', 'verification_code', 'created_at', 'content_hash', 'server_timestamp', 'signed_by_crm', 'signed_by_name', 'signed_by_specialty', 'signed_by_uf'],
  'medical_record_versions': ['id', 'record_id', 'tenant_id', 'version_number', 'content', 'changed_by', 'created_at'],
  'medical_records': ['id', 'tenant_id', 'patient_id', 'professional_id', 'appointment_id', 'record_type', 'subjective', 'objective', 'assessment', 'plan', 'notes', 'cid_codes', 'vital_signs', 'attachments', 'is_signed', 'signed_at', 'signed_by', 'created_at', 'updated_at', 'attendance_number', 'attendance_type', 'server_timestamp', 'signed_by_uf'],
  'medical_reports': ['id', 'tenant_id', 'patient_id', 'professional_id', 'medical_record_id', 'appointment_id', 'tipo', 'finalidade', 'historia_clinica', 'exame_fisico', 'exames_complementares', 'diagnostico', 'cid10', 'conclusao', 'observacoes', 'status', 'signed_at', 'created_at', 'updated_at'],
  'nursing_evolutions': ['id', 'tenant_id', 'patient_id', 'appointment_id', 'professional_id', 'evolution_date', 'nanda_code', 'nanda_diagnosis', 'nic_code', 'nic_intervention', 'nic_activities', 'noc_code', 'noc_outcome', 'noc_score_initial', 'noc_score_current', 'noc_score_target', 'notes', 'vital_signs', 'status', 'created_at', 'updated_at'],
  'prescription_refill_requests': ['id', 'tenant_id', 'patient_id', 'prescription_id', 'medication_name', 'reason', 'status', 'reviewed_by', 'reviewed_at', 'reviewer_notes', 'created_at'],
  'prescriptions': ['id', 'tenant_id', 'patient_id', 'professional_id', 'appointment_id', 'medications', 'notes', 'is_controlled', 'is_signed', 'signed_at', 'valid_until', 'created_at', 'updated_at', 'content_hash', 'digital_hash', 'server_timestamp', 'signed_by_crm', 'signed_by_name', 'signed_by_uf'],
  'procedures': ['id', 'tenant_id', 'name', 'description', 'duration_minutes', 'price', 'cost', 'commission_type', 'commission_value', 'category', 'tuss_code', 'is_active', 'requires_authorization', 'created_at', 'updated_at'],
  'prontuario_exports': ['id', 'tenant_id', 'client_id', 'client_name', 'client_cpf', 'include_prontuarios', 'include_receituarios', 'include_atestados', 'include_laudos', 'include_evolucoes', 'include_exames', 'include_anexos', 'data_inicio', 'data_fim', 'pdf_url', 'pdf_size_bytes', 'xml_url', 'xml_size_bytes', 'zip_url', 'zip_size_bytes', 'content_hash', 'hash_algorithm', 'tsa_timestamp_id', 'status', 'error_message', 'requested_by', 'requested_reason', 'download_count', 'last_download_at', 'expires_at', 'created_at'],
  'record_field_templates': ['id', 'tenant_id', 'specialty_id', 'name', 'fields', 'is_default', 'created_at', 'updated_at'],
  'referrals': ['id', 'tenant_id', 'patient_id', 'from_professional_id', 'to_specialty', 'to_professional_name', 'reason', 'urgency', 'notes', 'status', 'created_at', 'updated_at'],
  'services': ['id', 'tenant_id', 'name', 'description', 'duration_minutes', 'price', 'cost', 'commission_type', 'commission_value', 'category', 'tuss_code', 'is_active', 'requires_authorization', 'created_at', 'updated_at'],
  'transcription_jobs': ['id', 'tenant_id', 'user_id', 'status', 'audio_url', 'result_text', 'duration_ms', 'model', 'created_at', 'completed_at', 'error', 'job_name', 's3_uri', 'transcript'],
  'treatment_plan_items': ['id', 'plan_id', 'tenant_id', 'tooth_number', 'surface', 'procedure_name', 'procedure_code', 'cost', 'status', 'completed_at', 'sort_order', 'created_at', 'appointment_id', 'completed_by', 'discount_percent', 'notes', 'odontogram_tooth_id', 'procedure_category', 'quantity', 'region', 'total_price', 'updated_at'],
  'treatment_plans': ['id', 'tenant_id', 'patient_id', 'professional_id', 'title', 'status', 'total_cost', 'notes', 'approved_at', 'created_at', 'updated_at', 'approved_by_client', 'client_id', 'client_signature', 'description', 'discount_percent', 'discount_value', 'final_value', 'installments', 'odontogram_id', 'signature_ip'],
  'triage_records': ['id', 'tenant_id', 'patient_id', 'professional_id', 'priority', 'chief_complaint', 'vital_signs', 'notes', 'classification', 'created_at', 'allergies', 'appointment_id', 'blood_pressure_diastolic', 'blood_pressure_systolic', 'client_id', 'current_medications', 'heart_rate', 'height_cm', 'medical_history', 'oxygen_saturation', 'pain_scale', 'performed_by', 'respiratory_rate', 'status', 'temperature', 'triaged_at', 'weight_kg', 'updated_at'],
  'dental_images': ['id', 'tenant_id', 'patient_id', 'image_type', 'file_url', 'tooth_number', 'notes', 'taken_at', 'uploaded_by', 'created_at'],
  'odontogram_annotations': ['id', 'odontogram_id', 'tenant_id', 'tooth_number', 'annotation_type', 'content', 'created_by', 'created_at'],
  'odontogram_teeth': ['id', 'odontogram_id', 'tenant_id', 'tooth_number', 'status', 'notes', 'created_at', 'updated_at'],
  'odontogram_tooth_history': ['id', 'odontogram_id', 'tooth_number', 'previous_condition', 'new_condition', 'previous_surfaces', 'new_surfaces', 'previous_notes', 'new_notes', 'changed_by', 'changed_at', 'change_reason', 'ip_address', 'user_agent'],
  'odontogram_tooth_surfaces': ['id', 'tooth_id', 'tenant_id', 'surface', 'condition', 'procedure_done', 'created_at'],
  'odontograms': ['id', 'tenant_id', 'patient_id', 'professional_id', 'notes', 'created_at', 'updated_at'],
  'periogram_measurements': ['id', 'periogram_id', 'tenant_id', 'tooth_number', 'site', 'probing_depth', 'gingival_margin', 'bleeding', 'plaque', 'created_at'],
  'periograms': ['id', 'tenant_id', 'patient_id', 'professional_id', 'notes', 'created_at', 'updated_at'],
  'tuss_odonto_prices': ['id', 'tenant_id', 'tuss_code', 'description', 'default_price', 'category', 'is_active', 'created_at', 'updated_at'],
  'aesthetic_anamnesis': ['id', 'tenant_id', 'patient_id', 'fitzpatrick', 'skin_type', 'allergies', 'isotretinoin', 'pregnant', 'previous_procedures', 'expectations', 'created_at', 'updated_at'],
  'aesthetic_protocols': ['id', 'tenant_id', 'patient_id', 'name', 'procedure', 'total_sessions', 'completed_sessions', 'interval_days', 'next_session_date', 'notes', 'created_at'],
  'accounts_receivable': ['id', 'tenant_id', 'patient_id', 'appointment_id', 'amount', 'paid_amount', 'due_date', 'status', 'created_at', 'updated_at', 'amount_due', 'amount_paid', 'client_id', 'installments', 'notes', 'paid_at', 'payment_method', 'professional_id'],
  'asaas_checkout_sessions': ['checkout_session_id', 'tenant_id', 'created_at'],
  'asaas_webhook_alerts': ['id', 'created_at', 'event_id', 'event_type', 'reason', 'asaas_subscription_id', 'asaas_payment_id', 'checkout_session_id', 'payload'],
  'asaas_webhook_events': ['id', 'event_type', 'payload', 'processed', 'processed_at', 'created_at', 'attempts', 'event_key', 'last_attempt_at', 'last_error', 'received_at', 'status'],
  'bills_payable': ['id', 'tenant_id', 'description', 'amount', 'due_date', 'paid_at', 'status', 'category', 'supplier_id', 'cost_center_id', 'recurrence', 'created_at', 'updated_at', 'created_by', 'is_recurring', 'notes', 'paid_amount', 'payment_method', 'recurrence_type'],
  'bills_receivable': ['id', 'tenant_id', 'description', 'amount', 'due_date', 'received_at', 'status', 'patient_id', 'category', 'created_at', 'updated_at', 'client_id', 'created_by', 'notes', 'payment_method', 'received_amount'],
  'cash_movements': ['id', 'tenant_id', 'session_id', 'type', 'amount', 'description', 'created_by', 'created_at', 'reason'],
  'cash_sessions': ['id', 'tenant_id', 'opened_by', 'closed_by', 'opening_balance', 'closing_balance', 'opened_at', 'closed_at', 'notes', 'closing_balance_expected', 'closing_balance_reported', 'closing_difference', 'closing_notes', 'created_at', 'opening_notes', 'status', 'updated_at'],
  'commission_disputes': ['id', 'tenant_id', 'commission_id', 'professional_id', 'reason', 'status', 'admin_response', 'resolved_by', 'resolved_at', 'created_at', 'updated_at'],
  'commission_payments': ['id', 'tenant_id', 'professional_id', 'amount', 'period_start', 'period_end', 'payment_method', 'notes', 'paid_at', 'created_at'],
  'commission_rules': ['id', 'tenant_id', 'professional_id', 'procedure_id', 'commission_type', 'commission_value', 'min_threshold', 'tier_values', 'is_active', 'created_at', 'updated_at'],
  'cost_centers': ['id', 'tenant_id', 'name', 'description', 'is_active', 'created_at'],
  'discount_coupons': ['id', 'tenant_id', 'code', 'discount_percent', 'discount_amount', 'valid_until', 'max_uses', 'used_count', 'is_active', 'created_at'],
  'financial_transactions': ['id', 'tenant_id', 'appointment_id', 'type', 'category', 'amount', 'description', 'transaction_date', 'payment_method', 'cost_center_id', 'created_at', 'updated_at'],
  'nfse_invoices': ['id', 'tenant_id', 'patient_id', 'appointment_id', 'invoice_number', 'amount', 'status', 'external_id', 'xml_content', 'pdf_url', 'issued_at', 'created_at'],
  'order_items': ['id', 'order_id', 'tenant_id', 'item_type', 'item_id', 'item_name', 'quantity', 'unit_price', 'total', 'created_at'],
  'orders': ['id', 'tenant_id', 'patient_id', 'appointment_id', 'total', 'discount', 'status', 'notes', 'created_at', 'updated_at'],
  'payment_methods': ['id', 'tenant_id', 'name', 'type', 'is_active', 'created_at', 'code', 'sort_order'],
  'payments': ['id', 'tenant_id', 'order_id', 'payment_method_id', 'amount', 'status', 'external_id', 'created_at'],
  'professional_commissions': ['id', 'tenant_id', 'professional_id', 'appointment_id', 'service_name', 'service_price', 'commission_type', 'commission_value', 'commission_amount', 'status', 'paid_at', 'created_at', 'updated_at'],
  'professional_payment_accounts': ['id', 'tenant_id', 'professional_id', 'gateway_id', 'provider', 'recipient_id', 'wallet_id', 'account_id', 'pix_key', 'is_verified', 'verification_status', 'metadata', 'created_at', 'updated_at'],
  'professional_tier_tracking': ['id', 'tenant_id', 'professional_id', 'rule_id', 'current_tier_index', 'current_tier_value', 'monthly_revenue', 'last_checked_at', 'created_at', 'updated_at'],
  'salary_payments': ['id', 'tenant_id', 'professional_id', 'amount', 'reference_month', 'payment_date', 'payment_method', 'notes', 'status', 'created_at', 'updated_at'],
  'split_payment_logs': ['id', 'tenant_id', 'appointment_id', 'charge_id', 'provider', 'professional_id', 'total_amount', 'split_amount', 'clinic_amount', 'fee_amount', 'status', 'error_message', 'webhook_received_at', 'settled_at', 'metadata', 'created_at', 'updated_at'],
  'stripe_webhook_events': ['id', 'event_type', 'payload', 'processed', 'processed_at', 'created_at'],
  'product_categories': ['id', 'tenant_id', 'name', 'description', 'created_at'],
  'product_usage': ['id', 'tenant_id', 'product_id', 'patient_id', 'appointment_id', 'quantity', 'unit', 'batch_number', 'expiry_date', 'zone', 'procedure_type', 'notes', 'applied_by', 'applied_at', 'created_at'],
  'products': ['id', 'tenant_id', 'name', 'description', 'sku', 'barcode', 'cost', 'sale_price', 'quantity', 'min_quantity', 'category_id', 'is_active', 'is_controlled', 'batch_number', 'expiry_date', 'created_at', 'updated_at'],
  'purchase_items': ['id', 'purchase_id', 'product_id', 'tenant_id', 'quantity', 'unit_cost', 'total', 'created_at'],
  'purchases': ['id', 'tenant_id', 'supplier_id', 'total', 'status', 'notes', 'invoice_number', 'purchase_date', 'created_at', 'updated_at'],
  'stock_movements': ['id', 'tenant_id', 'product_id', 'quantity', 'movement_type', 'reason', 'created_by', 'batch_number', 'created_at', 'out_reason_type'],
  'suppliers': ['id', 'tenant_id', 'name', 'cnpj', 'email', 'phone', 'address', 'contact_name', 'is_active', 'created_at', 'updated_at'],
  'cashback_ledger': ['id', 'wallet_id', 'tenant_id', 'amount', 'type', 'description', 'appointment_id', 'created_at', 'actor_user_id', 'client_id', 'delta_amount', 'notes', 'order_id', 'reason'],
  'cashback_wallets': ['id', 'tenant_id', 'patient_id', 'balance', 'created_at', 'updated_at', 'client_id'],
  'goal_achievements': ['id', 'goal_id', 'tenant_id', 'achievement_type', 'achieved_at', 'metadata'],
  'goal_suggestions': ['id', 'tenant_id', 'suggested_by', 'title', 'description', 'goal_type', 'target_value', 'status', 'created_at'],
  'goal_templates': ['id', 'tenant_id', 'title', 'goal_type', 'default_target', 'description', 'created_at'],
  'goals': ['id', 'tenant_id', 'professional_id', 'title', 'description', 'goal_type', 'target_value', 'current_value', 'start_date', 'end_date', 'status', 'created_at', 'updated_at', 'archived_at', 'custom_end', 'custom_start', 'header_priority', 'parent_goal_id'],
  'health_credits_balance': ['id', 'tenant_id', 'patient_id', 'balance', 'lifetime_earned', 'lifetime_redeemed', 'tier', 'updated_at', 'created_at'],
  'health_credits_redemption_config': ['id', 'tenant_id', 'credits_per_real', 'min_redeem', 'max_discount_percent', 'is_active', 'created_at', 'updated_at'],
  'health_credits_rules': ['id', 'tenant_id', 'name', 'trigger_type', 'points', 'is_active', 'config', 'created_at'],
  'health_credits_transactions': ['id', 'tenant_id', 'patient_id', 'type', 'amount', 'balance_after', 'reason', 'reference_type', 'reference_id', 'created_by', 'created_at'],
  'loyalty_tiers': ['id', 'tenant_id', 'name', 'min_points', 'cashback_percent', 'benefits', 'sort_order', 'created_at'],
  'points_ledger': ['id', 'wallet_id', 'tenant_id', 'points', 'type', 'description', 'created_at'],
  'points_wallets': ['id', 'tenant_id', 'patient_id', 'balance', 'created_at', 'updated_at'],
  'voucher_redemptions': ['id', 'voucher_id', 'tenant_id', 'patient_id', 'appointment_id', 'discount_applied', 'created_at', 'order_id', 'redeemed_at', 'redeemed_by'],
  'vouchers': ['id', 'tenant_id', 'code', 'discount_type', 'discount_value', 'max_uses', 'used_count', 'valid_from', 'valid_until', 'is_active', 'created_at', 'created_by', 'expires_at', 'notes', 'status', 'valor', 'service_id'],
  'campaign_deliveries': ['id', 'campaign_id', 'tenant_id', 'patient_id', 'email', 'status', 'opened_at', 'clicked_at', 'created_at', 'client_id', 'error', 'provider_message_id', 'sent_at', 'to_email'],
  'campaigns': ['id', 'tenant_id', 'name', 'subject', 'html', 'preheader', 'banner_url', 'status', 'sent_count', 'scheduled_at', 'sent_at', 'created_at', 'updated_at', 'created_by'],
  'chat_channel_members': ['id', 'channel_id', 'user_id', 'tenant_id', 'joined_at', 'profile_id'],
  'chat_channels': ['id', 'tenant_id', 'name', 'description', 'is_private', 'created_by', 'created_at', 'is_default', 'updated_at'],
  'chat_read_status': ['id', 'profile_id', 'channel', 'channel_id', 'last_read_at', 'last_read_message_id'],
  'chatbot_conversations': ['id', 'tenant_id', 'phone', 'patient_id', 'state', 'context', 'last_interaction_at', 'created_at', 'client_id', 'last_message_at', 'updated_at'],
  'chatbot_messages': ['id', 'conversation_id', 'tenant_id', 'direction', 'content', 'message_id', 'created_at', 'message_type', 'metadata'],
  'chatbot_settings': ['id', 'tenant_id', 'greeting_message', 'business_hours', 'auto_booking', 'ai_enabled', 'created_at', 'updated_at', 'auto_confirm_booking', 'is_active', 'max_future_days', 'menu_message', 'business_days', 'outside_hours_message', 'business_hours_end', 'business_hours_start', 'welcome_message'],
  'feedback_analysis': ['id', 'feedback_id', 'tenant_id', 'sentiment', 'score', 'aspects', 'summary', 'action_required', 'suggested_action', 'analyzed_at'],
  'internal_messages': ['id', 'tenant_id', 'channel', 'sender_id', 'content', 'attachments', 'reply_to', 'edited_at', 'deleted_at', 'created_at', 'mentions'],
  'message_templates': ['id', 'tenant_id', 'name', 'channel', 'subject', 'body', 'variables', 'is_active', 'created_at'],
  'notification_logs': ['id', 'tenant_id', 'recipient_type', 'recipient_id', 'channel', 'template_type', 'status', 'metadata', 'error_details', 'created_at'],
  'notifications': ['id', 'tenant_id', 'user_id', 'title', 'message', 'type', 'read', 'read_at', 'action_url', 'metadata', 'created_at'],
  'nps_responses': ['id', 'tenant_id', 'patient_id', 'score', 'comment', 'source', 'created_at'],
  'push_notifications_log': ['id', 'tenant_id', 'user_id', 'subscription_id', 'notification_type', 'title', 'body', 'data', 'status', 'error_message', 'sent_at', 'delivered_at', 'clicked_at'],
  'push_subscriptions': ['id', 'user_id', 'tenant_id', 'endpoint', 'token', 'platform', 'is_active', 'created_at'],
  'sales_chatbot_conversations': ['id', 'phone', 'visitor_name', 'visitor_email', 'visitor_clinic_size', 'context', 'is_human_takeover', 'last_message_at', 'created_at', 'updated_at'],
  'sales_chatbot_messages': ['id', 'conversation_id', 'direction', 'content', 'created_at'],
  'sales_leads': ['id', 'phone', 'email', 'name', 'clinic_size', 'source', 'status', 'notes', 'metadata', 'created_at', 'updated_at'],
  'consent_forms': ['id', 'tenant_id', 'patient_id', 'title', 'content', 'signed_at', 'signature_url', 'created_at', 'updated_at'],
  'consent_signing_tokens': ['id', 'tenant_id', 'client_id', 'token', 'template_ids', 'expires_at', 'used_at', 'created_by', 'created_at'],
  'consent_templates': ['id', 'tenant_id', 'title', 'content', 'category', 'is_active', 'requires_photo', 'created_at', 'updated_at', 'slug', 'body_html', 'is_required', 'sort_order', 'template_type', 'pdf_storage_path', 'pdf_original_filename', 'pdf_file_size'],
  'document_signatures': ['id', 'tenant_id', 'patient_id', 'document_type', 'document_id', 'signature_method', 'signature_path', 'facial_photo_path', 'ip_address', 'user_agent', 'signed_at', 'created_at'],
  'document_verifications': ['id', 'document_type', 'document_id', 'document_hash', 'verification_result', 'verified_at', 'verifier_ip', 'verifier_user_agent', 'tenant_id'],
  'profile_certificates': ['id', 'profile_id', 'tenant_id', 'certificate_type', 'common_name', 'cpf_cnpj', 'issuer', 'serial_number', 'not_before', 'not_after', 'thumbprint', 'encrypted_pfx', 'encryption_iv', 'encryption_salt', 'a3_thumbprint', 'cloud_provider', 'cloud_credential_id', 'cloud_access_token', 'cloud_refresh_token', 'cloud_token_expires_at', 'is_active', 'is_default', 'nickname', 'created_at', 'updated_at', 'last_used_at'],
  'ai_conversation_messages': ['id', 'conversation_id', 'tenant_id', 'role', 'content', 'tool_calls', 'input_tokens', 'output_tokens', 'created_at', 'tokens_used', 'tool_input', 'tool_name'],
  'ai_conversations': ['id', 'tenant_id', 'user_id', 'title', 'model', 'total_input_tokens', 'total_output_tokens', 'created_at', 'updated_at', 'metadata', 'participant_type'],
  'ai_performance_metrics': ['id', 'tenant_id', 'function_name', 'latency_ms', 'input_tokens', 'output_tokens', 'model', 'success', 'error', 'created_at', 'completion_tokens', 'confidence_score', 'interaction_id', 'model_id', 'module_name', 'prompt_tokens', 'request_payload', 'response_summary', 'user_feedback', 'user_id'],
  'ai_usage_log': ['id', 'tenant_id', 'user_id', 'feature', 'input_tokens', 'output_tokens', 'cost_usd', 'created_at', 'metadata'],
  'hl7_connections': ['id', 'tenant_id', 'name', 'host', 'port', 'direction', 'message_types', 'is_active', 'auth_secret', 'created_at', 'updated_at'],
  'hl7_field_mappings': ['id', 'connection_id', 'tenant_id', 'hl7_field', 'local_table', 'local_column', 'transform', 'created_at'],
  'hl7_message_log': ['id', 'tenant_id', 'connection_id', 'direction', 'message_type', 'raw_message', 'status', 'error', 'created_at'],
  'hl7_patient_mapping': ['id', 'tenant_id', 'connection_id', 'external_patient_id', 'external_system', 'client_id', 'matched_by', 'confidence_score', 'is_verified', 'verified_by', 'verified_at', 'created_at', 'updated_at'],
  'incoming_rnds_bundles': ['id', 'tenant_id', 'bundle_type', 'fhir_bundle', 'bundle_id', 'source_cnes', 'source_name', 'source_uf', 'patient_cpf', 'patient_name', 'matched_patient_id', 'resource_types', 'resource_count', 'review_status', 'reviewed_by', 'reviewed_at', 'review_notes', 'received_at', 'processed_at', 'error_message', 'created_at'],
  'rnds_certificates': ['id', 'tenant_id', 'certificate_data', 'password_hash', 'valid_until', 'is_active', 'created_at'],
  'rnds_incoming_statistics': ['tenant_id', 'total_received', 'pending_count', 'accepted_count', 'rejected_count', 'merged_count', 'error_count', 'last_received_at'],
  'rnds_submissions': ['id', 'tenant_id', 'resource_type', 'resource_id', 'fhir_bundle', 'status', 'response', 'rnds_id', 'submitted_at', 'created_at'],
  'rnds_tokens': ['id', 'tenant_id', 'access_token', 'token_type', 'expires_at', 'created_at'],
  'tiss_glosa_appeals': ['id', 'tenant_id', 'tiss_guide_id', 'appeal_number', 'justification', 'requested_value', 'status', 'response_text', 'resolved_value', 'submitted_at', 'resolved_at', 'created_at', 'updated_at'],
  'tiss_guides': ['id', 'tenant_id', 'insurance_plan_id', 'appointment_id', 'lot_number', 'guide_number', 'guide_type', 'status', 'xml_content', 'tiss_version', 'submitted_at', 'response_code', 'response_message', 'created_at', 'glosa_code'],
  'tsa_config': ['id', 'tenant_id', 'provider', 'api_url', 'api_key_encrypted', 'certificate_path', 'certificate_password_encrypted', 'hash_algorithm', 'policy_oid', 'is_active', 'last_test_at', 'last_test_success', 'last_error', 'created_at', 'updated_at', 'created_by'],
  'tsa_timestamps': ['id', 'tenant_id', 'document_type', 'document_id', 'document_table', 'document_hash', 'hash_algorithm', 'status', 'timestamp_token', 'timestamp_token_base64', 'serial_number', 'tsa_time', 'tsa_policy_oid', 'tsa_provider', 'tsa_response', 'is_verified', 'verified_at', 'verification_result', 'error_message', 'retry_count', 'created_at', 'created_by'],
  'sngpc_agendamentos': ['id', 'tenant_id', 'ativo', 'frequencia', 'dia_semana', 'dia_mes', 'hora_execucao', 'ultima_execucao', 'proxima_execucao', 'ultima_transmissao_id', 'notificar_sucesso', 'notificar_erro', 'emails_notificacao', 'created_at', 'updated_at'],
  'sngpc_credenciais': ['id', 'tenant_id', 'username_encrypted', 'password_encrypted', 'cnpj', 'razao_social', 'cpf_responsavel', 'nome_responsavel', 'crf_responsavel', 'email_notificacao', 'ativo', 'ultima_autenticacao', 'token_expira_em', 'created_at', 'updated_at', 'created_by'],
  'sngpc_estoque': ['id', 'tenant_id', 'product_id', 'substance_name', 'quantity', 'unit', 'batch_number', 'expiry_date', 'last_updated', 'created_at'],
  'sngpc_movimentacoes': ['id', 'tenant_id', 'estoque_id', 'movement_type', 'quantity', 'prescription_id', 'patient_id', 'professional_id', 'notes', 'created_at'],
  'sngpc_notificacoes_receita': ['id', 'tenant_id', 'numero', 'serie', 'tipo_receituario', 'lista', 'medicamento_codigo', 'medicamento_nome', 'quantidade', 'posologia', 'duracao_dias', 'paciente_id', 'paciente_nome', 'paciente_endereco', 'paciente_cidade', 'paciente_uf', 'paciente_cpf', 'prescriptor_id', 'prescriptor_nome', 'prescriptor_crm', 'prescriptor_uf', 'data_emissao', 'data_validade', 'status', 'data_dispensacao', 'movimentacao_id', 'created_at', 'updated_at'],
  'sngpc_sequencial': ['id', 'tenant_id', 'tipo_receituario', 'ano', 'ultimo_numero', 'created_at', 'updated_at'],
  'sngpc_tracked_prescriptions': ['id', 'tenant_id', 'prescription_id', 'patient_id', 'professional_id', 'anvisa_lista', 'recipe_type', 'medication_name', 'medication_dosage', 'medication_quantity', 'medication_duration_days', 'dispensed_at', 'dispensed_by', 'dispensed_pharmacy', 'dispensation_status', 'sngpc_notified', 'sngpc_notification_date', 'sngpc_protocol', 'prescribed_at', 'expires_at', 'created_at', 'updated_at'],
  'sngpc_transmissoes_log': ['id', 'transmissao_id', 'acao', 'status_anterior', 'status_novo', 'request_payload', 'response_payload', 'http_status', 'erro_mensagem', 'executado_por', 'executado_em', 'ip_address', 'user_agent'],
  'sngpc_transmissoes': ['id', 'tenant_id', 'period_start', 'period_end', 'status', 'xml_content', 'response', 'transmitted_at', 'created_at'],
  'dpo_config': ['id', 'tenant_id', 'nome', 'email', 'telefone', 'cpf', 'formacao', 'certificacoes', 'publicado', 'url_publicacao', 'data_nomeacao', 'email_publico', 'telefone_publico', 'ativo', 'created_at', 'updated_at'],
  'lgpd_consentimentos': ['id', 'tenant_id', 'titular_id', 'titular_email', 'titular_nome', 'finalidade', 'descricao', 'dados_coletados', 'consentido', 'data_consentimento', 'data_revogacao', 'ip_address', 'user_agent', 'metodo', 'evidencia_url', 'validade_dias', 'data_expiracao', 'created_at'],
  'lgpd_data_requests': ['id', 'tenant_id', 'patient_id', 'request_type', 'status', 'requested_at', 'completed_at', 'notes', 'created_at'],
  'lgpd_incidentes': ['id', 'tenant_id', 'titulo', 'descricao', 'tipo', 'severidade', 'dados_afetados', 'categorias_dados', 'quantidade_titulares_afetados', 'titulares_identificados', 'data_ocorrencia', 'data_deteccao', 'data_contencao', 'data_resolucao', 'status', 'requer_notificacao_anpd', 'notificacao_anpd_enviada', 'data_notificacao_anpd', 'protocolo_anpd', 'prazo_notificacao', 'requer_notificacao_titulares', 'notificacao_titulares_enviada', 'data_notificacao_titulares', 'medidas_contencao', 'medidas_remediacao', 'medidas_preventivas', 'responsavel_investigacao', 'responsavel_comunicacao', 'evidencias', 'timeline_acoes', 'post_mortem', 'licoes_aprendidas', 'created_at', 'updated_at'],
  'lgpd_retention_policies': ['id', 'tenant_id', 'data_category', 'retention_years', 'legal_basis', 'is_active', 'created_at'],
  'lgpd_solicitacoes': ['id', 'tenant_id', 'titular_nome', 'titular_email', 'titular_cpf', 'titular_telefone', 'tipo', 'descricao', 'dados_solicitados', 'status', 'data_solicitacao', 'prazo_resposta', 'data_resposta', 'resposta', 'motivo_negativa', 'arquivos_resposta', 'atendido_por', 'historico', 'created_at', 'updated_at'],
  'retention_deletion_attempts': ['id', 'tenant_id', 'user_id', 'table_name', 'record_id', 'client_id', 'client_name', 'retention_expires_at', 'attempted_at', 'blocked', 'reason'],
  'ripd_reports': ['id', 'tenant_id', 'version', 'title', 'identificacao_agentes', 'necessidade_proporcionalidade', 'identificacao_riscos', 'medidas_salvaguardas', 'dados_pessoais_tratados', 'bases_legais', 'finalidades', 'riscos_identificados', 'matriz_riscos', 'medidas_tecnicas', 'medidas_administrativas', 'status', 'approved_by', 'approved_at', 'next_review_at', 'review_notes', 'pdf_url', 'created_by', 'created_at', 'updated_at'],
  'admin_audit_logs': ['id', 'tenant_id', 'user_id', 'action', 'target_type', 'target_id', 'before_data', 'after_data', 'ip_address', 'created_at', 'actor_user_id', 'entity_id', 'entity_type', 'metadata'],
  'adverse_events_attachments': ['id', 'adverse_event_id', 'nome_arquivo', 'tipo_arquivo', 'url', 'uploaded_by', 'created_at'],
  'adverse_events_history': ['id', 'adverse_event_id', 'user_id', 'action', 'old_status', 'new_status', 'comentario', 'dados_alterados', 'created_at'],
  'adverse_events': ['id', 'tenant_id', 'patient_id', 'reported_by', 'event_type', 'severity', 'description', 'root_cause', 'corrective_actions', 'status', 'created_at', 'updated_at', 'acoes_corretivas', 'acoes_preventivas', 'circunstancias', 'conclusao', 'data_evento', 'data_notificacao', 'data_notificacao_anvisa', 'fatores_contribuintes', 'licoes_aprendidas', 'local_evento', 'notificado_por', 'prazo_acoes', 'professional_id', 'protocolo_anvisa', 'responsavel_investigacao', 'setor', 'testemunhas', 'tipo_outro'],
  'audit_logs': ['id', 'tenant_id', 'user_id', 'action', 'resource_type', 'resource_id', 'details', 'ip_address', 'user_agent', 'created_at', 'actor_role', 'actor_user_id', 'entity_id', 'entity_type', 'metadata'],
  'backup_logs': ['id', 'tenant_id', 'backup_id', 'backup_type', 'started_at', 'completed_at', 'status', 'size_bytes', 'tables_count', 'records_count', 'duration_seconds', 'checksum_algorithm', 'checksum_value', 'verification_checksum', 'verified_at', 'verified_by', 'storage_location', 'storage_provider', 'retention_days', 'expires_at', 'metadata', 'error_message', 'created_at', 'backup_name', 'compressed_size_bytes', 'deleted_at', 'hash_algorithm', 'is_deleted', 'is_verified', 'restore_test_success', 'storage_path', 'storage_region', 'verification_hash'],
  'backup_retention_policies': ['id', 'tenant_id', 'name', 'description', 'backup_type', 'retention_days', 'min_copies', 'schedule_cron', 'enabled', 'notify_on_failure', 'notify_on_success', 'notification_emails', 'created_at', 'updated_at'],
  'backup_verifications': ['id', 'tenant_id', 'backup_log_id', 'verification_type', 'status', 'checksum_match', 'tables_verified', 'records_verified', 'errors_found', 'warnings_found', 'details', 'notes', 'performed_by', 'performed_at', 'created_at'],
  'ona_indicators': ['id', 'tenant_id', 'indicator_code', 'indicator_name', 'value', 'target_value', 'period_start', 'period_end', 'created_at'],
  'sbis_documentation': ['id', 'tenant_id', 'category', 'subcategory', 'requirement_code', 'title', 'description', 'content', 'evidence_type', 'evidence_url', 'screenshots', 'compliance_status', 'compliance_notes', 'last_reviewed_at', 'reviewed_by', 'created_at', 'updated_at'],
  'automation_dispatch_logs': ['id', 'automation_id', 'tenant_id', 'status', 'target', 'error', 'created_at', 'channel', 'details', 'dispatch_period', 'entity_id', 'entity_type'],
  'automations': ['id', 'tenant_id', 'name', 'trigger_type', 'trigger_config', 'action_type', 'action_config', 'is_active', 'last_run_at', 'run_count', 'created_at', 'updated_at', 'channel', 'message_template'],
  'report_definitions': ['id', 'tenant_id', 'name', 'description', 'category', 'is_template', 'template_id', 'base_table', 'joins', 'fields', 'default_filters', 'group_by', 'order_by', 'chart_type', 'chart_config', 'icon', 'color', 'is_active', 'is_public', 'created_by', 'created_at', 'updated_at'],
  'report_executions': ['id', 'tenant_id', 'report_definition_id', 'saved_report_id', 'schedule_id', 'status', 'parameters', 'result_url', 'error_message', 'rows_count', 'execution_time_ms', 'output_format', 'file_size_bytes', 'executed_by', 'executed_at'],
  'report_schedules': ['id', 'tenant_id', 'saved_report_id', 'schedule_type', 'cron_expression', 'next_run_at', 'last_run_at', 'is_active', 'output_format', 'recipients', 'created_at', 'updated_at'],
  'user_saved_reports': ['id', 'tenant_id', 'user_id', 'report_definition_id', 'name', 'custom_filters', 'custom_fields', 'custom_group_by', 'custom_chart_config', 'is_favorite', 'last_run_at', 'run_count', 'created_at', 'updated_at'],
  'contact_messages': ['id', 'name', 'email', 'phone', 'subject', 'message', 'source', 'status', 'created_at'],
  'support_messages': ['id', 'ticket_id', 'sender_id', 'sender_type', 'content', 'created_at'],
  'support_tickets': ['id', 'tenant_id', 'user_id', 'subject', 'description', 'priority', 'status', 'category', 'created_at', 'updated_at'],
  'offline_cache_metadata': ['id', 'user_id', 'tenant_id', 'cache_key', 'data_type', 'record_count', 'last_synced_at', 'sync_version', 'size_bytes', 'created_at'],
  'user_keyboard_shortcuts': ['id', 'user_id', 'action_id', 'keys', 'is_enabled', 'created_at', 'updated_at'],
  'user_notification_preferences': ['id', 'user_id', 'tenant_id', 'email_enabled', 'push_enabled', 'sms_enabled', 'quiet_hours_start', 'quiet_hours_end', 'created_at', 'updated_at', 'appointment_cancelled', 'appointment_completed', 'appointment_created', 'commission_generated', 'commission_paid', 'goal_approved', 'goal_reached', 'goal_rejected', 'goal_reminder'],
  'user_tour_progress': ['id', 'user_id', 'tenant_id', 'tour_id', 'completed', 'completed_at', 'created_at', 'step_index', 'tour_key', 'updated_at'],
  'user_video_progress': ['id', 'user_id', 'video_id', 'watched_seconds', 'completed', 'completed_at', 'last_watched_at', 'created_at'],
  'video_tutorials': ['id', 'title', 'description', 'video_url', 'thumbnail_url', 'duration_seconds', 'category', 'feature_key', 'sort_order', 'is_active', 'created_at', 'updated_at'],
};
