-- ================================================================
-- MIGRATION: Fix ALL missing columns + missing tables
-- Generated by deep_audit_fix.py
-- ================================================================

BEGIN;

-- ========================
-- MISSING TABLES
-- ========================

-- ========================
-- MISSING COLUMNS
-- ========================

-- Table: accounts_receivable (8 columns)
ALTER TABLE public.accounts_receivable ADD COLUMN IF NOT EXISTS amount_due NUMERIC(10,2) NOT NULL DEFAULT 0;
ALTER TABLE public.accounts_receivable ADD COLUMN IF NOT EXISTS amount_paid NUMERIC(10,2) NOT NULL DEFAULT 0;
ALTER TABLE public.accounts_receivable ADD COLUMN IF NOT EXISTS client_id UUID REFERENCES public.patients(id) ON DELETE SET NULL;
ALTER TABLE public.accounts_receivable ADD COLUMN IF NOT EXISTS installments INTEGER DEFAULT 1;
ALTER TABLE public.accounts_receivable ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.accounts_receivable ADD COLUMN IF NOT EXISTS paid_at TIMESTAMPTZ;
ALTER TABLE public.accounts_receivable ADD COLUMN IF NOT EXISTS payment_method TEXT;
ALTER TABLE public.accounts_receivable ADD COLUMN IF NOT EXISTS professional_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL;

-- Table: admin_audit_logs (4 columns)
ALTER TABLE public.admin_audit_logs ADD COLUMN IF NOT EXISTS actor_user_id UUID NOT NULL;
ALTER TABLE public.admin_audit_logs ADD COLUMN IF NOT EXISTS entity_id TEXT;
ALTER TABLE public.admin_audit_logs ADD COLUMN IF NOT EXISTS entity_type TEXT NOT NULL;
ALTER TABLE public.admin_audit_logs ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb;

-- Table: adverse_events (18 columns)
ALTER TABLE public.adverse_events ADD COLUMN IF NOT EXISTS acoes_corretivas TEXT;
ALTER TABLE public.adverse_events ADD COLUMN IF NOT EXISTS acoes_preventivas TEXT;
ALTER TABLE public.adverse_events ADD COLUMN IF NOT EXISTS circunstancias TEXT;
ALTER TABLE public.adverse_events ADD COLUMN IF NOT EXISTS conclusao TEXT;
ALTER TABLE public.adverse_events ADD COLUMN IF NOT EXISTS data_evento TIMESTAMPTZ NOT NULL;
ALTER TABLE public.adverse_events ADD COLUMN IF NOT EXISTS data_notificacao TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.adverse_events ADD COLUMN IF NOT EXISTS data_notificacao_anvisa TIMESTAMPTZ;
ALTER TABLE public.adverse_events ADD COLUMN IF NOT EXISTS fatores_contribuintes TEXT[];
ALTER TABLE public.adverse_events ADD COLUMN IF NOT EXISTS licoes_aprendidas TEXT;
ALTER TABLE public.adverse_events ADD COLUMN IF NOT EXISTS local_evento TEXT;
ALTER TABLE public.adverse_events ADD COLUMN IF NOT EXISTS notificado_por UUID REFERENCES public.profiles(id);
ALTER TABLE public.adverse_events ADD COLUMN IF NOT EXISTS prazo_acoes DATE;
ALTER TABLE public.adverse_events ADD COLUMN IF NOT EXISTS professional_id UUID REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.adverse_events ADD COLUMN IF NOT EXISTS protocolo_anvisa TEXT;
ALTER TABLE public.adverse_events ADD COLUMN IF NOT EXISTS responsavel_investigacao UUID REFERENCES public.profiles(id);
ALTER TABLE public.adverse_events ADD COLUMN IF NOT EXISTS setor TEXT;
ALTER TABLE public.adverse_events ADD COLUMN IF NOT EXISTS testemunhas TEXT;
ALTER TABLE public.adverse_events ADD COLUMN IF NOT EXISTS tipo_outro TEXT;

-- Table: ai_conversation_messages (3 columns)
ALTER TABLE public.ai_conversation_messages ADD COLUMN IF NOT EXISTS tokens_used INTEGER DEFAULT 0;
ALTER TABLE public.ai_conversation_messages ADD COLUMN IF NOT EXISTS tool_input JSONB;
ALTER TABLE public.ai_conversation_messages ADD COLUMN IF NOT EXISTS tool_name TEXT;

-- Table: ai_conversations (2 columns)
ALTER TABLE public.ai_conversations ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}';
ALTER TABLE public.ai_conversations ADD COLUMN IF NOT EXISTS participant_type TEXT NOT NULL CHECK (participant_type IN ('professional', 'patient'));

-- Table: ai_performance_metrics (10 columns)
ALTER TABLE public.ai_performance_metrics ADD COLUMN IF NOT EXISTS completion_tokens integer DEFAULT 0;
ALTER TABLE public.ai_performance_metrics ADD COLUMN IF NOT EXISTS confidence_score numeric(5,2) CHECK (confidence_score >= 0 AND confidence_score <= 100);
ALTER TABLE public.ai_performance_metrics ADD COLUMN IF NOT EXISTS interaction_id uuid NOT NULL DEFAULT gen_random_uuid();
ALTER TABLE public.ai_performance_metrics ADD COLUMN IF NOT EXISTS model_id text;
ALTER TABLE public.ai_performance_metrics ADD COLUMN IF NOT EXISTS module_name text NOT NULL CHECK (module_name IN ('copilot','gps','triage','automation','chatbot'));
ALTER TABLE public.ai_performance_metrics ADD COLUMN IF NOT EXISTS prompt_tokens integer DEFAULT 0;
ALTER TABLE public.ai_performance_metrics ADD COLUMN IF NOT EXISTS request_payload jsonb DEFAULT '{}';
ALTER TABLE public.ai_performance_metrics ADD COLUMN IF NOT EXISTS response_summary text;
ALTER TABLE public.ai_performance_metrics ADD COLUMN IF NOT EXISTS user_feedback text CHECK (user_feedback IS NULL OR user_feedback IN ('accepted','rejected','partial'));
ALTER TABLE public.ai_performance_metrics ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL;

-- Table: appointment_cashback_earnings (3 columns)
ALTER TABLE public.appointment_cashback_earnings ADD COLUMN IF NOT EXISTS client_id uuid not null REFERENCES public.patients(id) on delete cascade;
ALTER TABLE public.appointment_cashback_earnings ADD COLUMN IF NOT EXISTS earned_amount numeric not null;
ALTER TABLE public.appointment_cashback_earnings ADD COLUMN IF NOT EXISTS earned_at timestamptz not null default now();

-- Table: appointment_package_consumptions (1 columns)
ALTER TABLE public.appointment_package_consumptions ADD COLUMN IF NOT EXISTS consumed_at timestamptz not null default now();

-- Table: appointments (9 columns)
ALTER TABLE public.appointments ADD COLUMN IF NOT EXISTS booked_by_id UUID REFERENCES public.profiles(user_id) ON DELETE SET NULL;
ALTER TABLE public.appointments ADD COLUMN IF NOT EXISTS client_id UUID REFERENCES public.patients(id) ON DELETE SET NULL;
ALTER TABLE public.appointments ADD COLUMN IF NOT EXISTS confirmation_sent_4h BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE public.appointments ADD COLUMN IF NOT EXISTS confirmed_at TIMESTAMPTZ;
ALTER TABLE public.appointments ADD COLUMN IF NOT EXISTS created_via text not null default 'internal';
ALTER TABLE public.appointments ADD COLUMN IF NOT EXISTS service_id UUID REFERENCES public.procedures(id) ON DELETE SET NULL;
ALTER TABLE public.appointments ADD COLUMN IF NOT EXISTS source text NULL;
ALTER TABLE public.appointments ADD COLUMN IF NOT EXISTS telemedicine_token uuid UNIQUE DEFAULT NULL;
ALTER TABLE public.appointments ADD COLUMN IF NOT EXISTS unit_id UUID REFERENCES public.clinic_units(id) ON DELETE SET NULL;

-- Table: asaas_webhook_events (6 columns)
ALTER TABLE public.asaas_webhook_events ADD COLUMN IF NOT EXISTS attempts integer not null default 0;
ALTER TABLE public.asaas_webhook_events ADD COLUMN IF NOT EXISTS event_key text not null unique;
ALTER TABLE public.asaas_webhook_events ADD COLUMN IF NOT EXISTS last_attempt_at timestamptz;
ALTER TABLE public.asaas_webhook_events ADD COLUMN IF NOT EXISTS last_error text;
ALTER TABLE public.asaas_webhook_events ADD COLUMN IF NOT EXISTS received_at timestamptz not null default now();
ALTER TABLE public.asaas_webhook_events ADD COLUMN IF NOT EXISTS status text not null default 'received';

-- Table: audit_logs (5 columns)
ALTER TABLE public.audit_logs ADD COLUMN IF NOT EXISTS actor_role text;
ALTER TABLE public.audit_logs ADD COLUMN IF NOT EXISTS actor_user_id uuid;
ALTER TABLE public.audit_logs ADD COLUMN IF NOT EXISTS entity_id text;
ALTER TABLE public.audit_logs ADD COLUMN IF NOT EXISTS entity_type text NOT NULL;
ALTER TABLE public.audit_logs ADD COLUMN IF NOT EXISTS metadata jsonb NOT NULL DEFAULT '{}'::jsonb;

-- Table: automation_dispatch_logs (5 columns)
ALTER TABLE public.automation_dispatch_logs ADD COLUMN IF NOT EXISTS channel text not null;
ALTER TABLE public.automation_dispatch_logs ADD COLUMN IF NOT EXISTS details jsonb not null default '{}'::jsonb;
ALTER TABLE public.automation_dispatch_logs ADD COLUMN IF NOT EXISTS dispatch_period text not null default 'once';
ALTER TABLE public.automation_dispatch_logs ADD COLUMN IF NOT EXISTS entity_id uuid not null;
ALTER TABLE public.automation_dispatch_logs ADD COLUMN IF NOT EXISTS entity_type text not null;

-- Table: automations (2 columns)
ALTER TABLE public.automations ADD COLUMN IF NOT EXISTS channel text not null;
ALTER TABLE public.automations ADD COLUMN IF NOT EXISTS message_template text not null;

-- Table: backup_logs (10 columns)
ALTER TABLE public.backup_logs ADD COLUMN IF NOT EXISTS backup_name VARCHAR(200) NOT NULL;
ALTER TABLE public.backup_logs ADD COLUMN IF NOT EXISTS compressed_size_bytes BIGINT;
ALTER TABLE public.backup_logs ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE public.backup_logs ADD COLUMN IF NOT EXISTS hash_algorithm VARCHAR(20) DEFAULT 'SHA-256';
ALTER TABLE public.backup_logs ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT false;
ALTER TABLE public.backup_logs ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT false;
ALTER TABLE public.backup_logs ADD COLUMN IF NOT EXISTS restore_test_success BOOLEAN;
ALTER TABLE public.backup_logs ADD COLUMN IF NOT EXISTS storage_path TEXT;
ALTER TABLE public.backup_logs ADD COLUMN IF NOT EXISTS storage_region VARCHAR(50);
ALTER TABLE public.backup_logs ADD COLUMN IF NOT EXISTS verification_hash TEXT;

-- Table: bills_payable (6 columns)
ALTER TABLE public.bills_payable ADD COLUMN IF NOT EXISTS created_by uuid references public.profiles(id) on delete set null;
ALTER TABLE public.bills_payable ADD COLUMN IF NOT EXISTS is_recurring boolean not null default false;
ALTER TABLE public.bills_payable ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.bills_payable ADD COLUMN IF NOT EXISTS paid_amount numeric(12,2);
ALTER TABLE public.bills_payable ADD COLUMN IF NOT EXISTS payment_method text;
ALTER TABLE public.bills_payable ADD COLUMN IF NOT EXISTS recurrence_type text;

-- Table: bills_receivable (5 columns)
ALTER TABLE public.bills_receivable ADD COLUMN IF NOT EXISTS client_id uuid REFERENCES public.patients(id) on delete set null;
ALTER TABLE public.bills_receivable ADD COLUMN IF NOT EXISTS created_by uuid references public.profiles(id) on delete set null;
ALTER TABLE public.bills_receivable ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.bills_receivable ADD COLUMN IF NOT EXISTS payment_method text;
ALTER TABLE public.bills_receivable ADD COLUMN IF NOT EXISTS received_amount numeric(12,2);

-- Table: campaign_deliveries (5 columns)
ALTER TABLE public.campaign_deliveries ADD COLUMN IF NOT EXISTS client_id uuid not null REFERENCES public.patients(id) on delete cascade;
ALTER TABLE public.campaign_deliveries ADD COLUMN IF NOT EXISTS error text;
ALTER TABLE public.campaign_deliveries ADD COLUMN IF NOT EXISTS provider_message_id text;
ALTER TABLE public.campaign_deliveries ADD COLUMN IF NOT EXISTS sent_at timestamptz;
ALTER TABLE public.campaign_deliveries ADD COLUMN IF NOT EXISTS to_email text not null;

-- Table: campaigns (1 columns)
ALTER TABLE public.campaigns ADD COLUMN IF NOT EXISTS created_by uuid;

-- Table: cash_movements (1 columns)
ALTER TABLE public.cash_movements ADD COLUMN IF NOT EXISTS reason text NULL;

-- Table: cash_sessions (8 columns)
ALTER TABLE public.cash_sessions ADD COLUMN IF NOT EXISTS closing_balance_expected numeric(12,2) NULL;
ALTER TABLE public.cash_sessions ADD COLUMN IF NOT EXISTS closing_balance_reported numeric(12,2) NULL;
ALTER TABLE public.cash_sessions ADD COLUMN IF NOT EXISTS closing_difference numeric(12,2) NULL;
ALTER TABLE public.cash_sessions ADD COLUMN IF NOT EXISTS closing_notes text NULL;
ALTER TABLE public.cash_sessions ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.cash_sessions ADD COLUMN IF NOT EXISTS opening_notes text NULL;
ALTER TABLE public.cash_sessions ADD COLUMN IF NOT EXISTS status public.cash_session_status NOT NULL DEFAULT 'open';
ALTER TABLE public.cash_sessions ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

-- Table: cashback_ledger (6 columns)
ALTER TABLE public.cashback_ledger ADD COLUMN IF NOT EXISTS actor_user_id uuid;
ALTER TABLE public.cashback_ledger ADD COLUMN IF NOT EXISTS client_id uuid not null REFERENCES public.patients(id) on delete cascade;
ALTER TABLE public.cashback_ledger ADD COLUMN IF NOT EXISTS delta_amount numeric not null;
ALTER TABLE public.cashback_ledger ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.cashback_ledger ADD COLUMN IF NOT EXISTS order_id uuid references public.orders(id) on delete set null;
ALTER TABLE public.cashback_ledger ADD COLUMN IF NOT EXISTS reason public.cashback_ledger_reason not null;

-- Table: cashback_wallets (1 columns)
ALTER TABLE public.cashback_wallets ADD COLUMN IF NOT EXISTS client_id uuid not null REFERENCES public.patients(id) on delete cascade;

-- Table: chat_channel_members (1 columns)
ALTER TABLE public.chat_channel_members ADD COLUMN IF NOT EXISTS profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE;

-- Table: chat_channels (2 columns)
ALTER TABLE public.chat_channels ADD COLUMN IF NOT EXISTS is_default BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE public.chat_channels ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

-- Table: chatbot_conversations (3 columns)
ALTER TABLE public.chatbot_conversations ADD COLUMN IF NOT EXISTS client_id UUID REFERENCES public.patients(id) ON DELETE SET NULL;
ALTER TABLE public.chatbot_conversations ADD COLUMN IF NOT EXISTS last_message_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE public.chatbot_conversations ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

-- Table: chatbot_messages (2 columns)
ALTER TABLE public.chatbot_messages ADD COLUMN IF NOT EXISTS message_type TEXT NOT NULL DEFAULT 'text';
ALTER TABLE public.chatbot_messages ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}';

-- Table: chatbot_settings (10 columns)
ALTER TABLE public.chatbot_settings ADD COLUMN IF NOT EXISTS auto_confirm_booking BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE public.chatbot_settings ADD COLUMN IF NOT EXISTS business_days INT[] NOT NULL DEFAULT '{1;
ALTER TABLE public.chatbot_settings ADD COLUMN IF NOT EXISTS business_hours_end TIME NOT NULL DEFAULT '18:00';
ALTER TABLE public.chatbot_settings ADD COLUMN IF NOT EXISTS business_hours_start TIME NOT NULL DEFAULT '08:00';
ALTER TABLE public.chatbot_settings ADD COLUMN IF NOT EXISTS das 8h às 18h. Deixe sua mensagem que retornaremos assim que possível.';
ALTER TABLE public.chatbot_settings ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE public.chatbot_settings ADD COLUMN IF NOT EXISTS max_future_days INT NOT NULL DEFAULT 30;
ALTER TABLE public.chatbot_settings ADD COLUMN IF NOT EXISTS menu_message TEXT NOT NULL DEFAULT 'Escolha uma opção:';
ALTER TABLE public.chatbot_settings ADD COLUMN IF NOT EXISTS outside_hours_message TEXT NOT NULL DEFAULT 'Nosso horário de atendimento é de segunda a sexta;
ALTER TABLE public.chatbot_settings ADD COLUMN IF NOT EXISTS welcome_message TEXT NOT NULL DEFAULT 'Olá! 👋 Bem-vindo(a) à nossa clínica. Como posso ajudá-lo(a)?';

-- Table: client_marketing_preferences (2 columns)
ALTER TABLE public.client_marketing_preferences ADD COLUMN IF NOT EXISTS client_id uuid not null REFERENCES public.patients(id) on delete cascade;
ALTER TABLE public.client_marketing_preferences ADD COLUMN IF NOT EXISTS marketing_opt_out boolean not null default false;

-- Table: client_package_ledger (4 columns)
ALTER TABLE public.client_package_ledger ADD COLUMN IF NOT EXISTS actor_user_id uuid;
ALTER TABLE public.client_package_ledger ADD COLUMN IF NOT EXISTS delta_sessions integer not null;
ALTER TABLE public.client_package_ledger ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.client_package_ledger ADD COLUMN IF NOT EXISTS reason public.client_package_ledger_reason not null;

-- Table: client_packages (6 columns)
ALTER TABLE public.client_packages ADD COLUMN IF NOT EXISTS client_id uuid not null REFERENCES public.patients(id) on delete cascade;
ALTER TABLE public.client_packages ADD COLUMN IF NOT EXISTS created_by uuid;
ALTER TABLE public.client_packages ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.client_packages ADD COLUMN IF NOT EXISTS purchased_at timestamptz not null default now();
ALTER TABLE public.client_packages ADD COLUMN IF NOT EXISTS remaining_sessions integer not null check (remaining_sessions >= 0);
ALTER TABLE public.client_packages ADD COLUMN IF NOT EXISTS service_id uuid not null REFERENCES public.procedures(id) on delete restrict;

-- Table: clients (4 columns)
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS cns VARCHAR(15);
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS date_of_birth DATE;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS last_appointment_date DATE;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS retention_expires_at DATE;

-- Table: commission_payments (9 columns)
ALTER TABLE public.commission_payments ADD COLUMN IF NOT EXISTS appointment_id UUID REFERENCES public.appointments(id) ON DELETE SET NULL;
ALTER TABLE public.commission_payments ADD COLUMN IF NOT EXISTS commission_config_id UUID REFERENCES public.professional_commissions(id) ON DELETE SET NULL;
ALTER TABLE public.commission_payments ADD COLUMN IF NOT EXISTS commission_type public.commission_type NOT NULL;
ALTER TABLE public.commission_payments ADD COLUMN IF NOT EXISTS commission_value DECIMAL(10,2) NOT NULL CHECK (commission_value >= 0);
ALTER TABLE public.commission_payments ADD COLUMN IF NOT EXISTS paid_by UUID REFERENCES public.profiles(user_id) ON DELETE SET NULL;
ALTER TABLE public.commission_payments ADD COLUMN IF NOT EXISTS payment_date TIMESTAMPTZ;
ALTER TABLE public.commission_payments ADD COLUMN IF NOT EXISTS service_price NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE public.commission_payments ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid'));
ALTER TABLE public.commission_payments ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

-- Table: commission_rules (3 columns)
ALTER TABLE public.commission_rules ADD COLUMN IF NOT EXISTS insurance_id UUID REFERENCES public.insurance_plans(id) ON DELETE CASCADE;
ALTER TABLE public.commission_rules ADD COLUMN IF NOT EXISTS procedure_code TEXT;
ALTER TABLE public.commission_rules ADD COLUMN IF NOT EXISTS value DECIMAL(10,2) NOT NULL CHECK (value >= 0);

-- Table: consent_forms (10 columns)
ALTER TABLE public.consent_forms ADD COLUMN IF NOT EXISTS appointment_id UUID REFERENCES public.appointments(id) ON DELETE SET NULL;
ALTER TABLE public.consent_forms ADD COLUMN IF NOT EXISTS client_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.consent_forms ADD COLUMN IF NOT EXISTS form_type TEXT NOT NULL DEFAULT 'geral';
ALTER TABLE public.consent_forms ADD COLUMN IF NOT EXISTS ip_address TEXT;
ALTER TABLE public.consent_forms ADD COLUMN IF NOT EXISTS is_revoked BOOLEAN DEFAULT FALSE;
ALTER TABLE public.consent_forms ADD COLUMN IF NOT EXISTS revocation_reason TEXT;
ALTER TABLE public.consent_forms ADD COLUMN IF NOT EXISTS revoked_at TIMESTAMPTZ;
ALTER TABLE public.consent_forms ADD COLUMN IF NOT EXISTS signature_data TEXT;
ALTER TABLE public.consent_forms ADD COLUMN IF NOT EXISTS signed_by_name TEXT;
ALTER TABLE public.consent_forms ADD COLUMN IF NOT EXISTS witnessed_by UUID REFERENCES public.profiles(id);

-- Table: consent_templates (6 columns)
ALTER TABLE public.consent_templates ADD COLUMN IF NOT EXISTS contrato body_html TEXT NOT NULL DEFAULT '';
ALTER TABLE public.consent_templates ADD COLUMN IF NOT EXISTS pdf_file_size INTEGER;
ALTER TABLE public.consent_templates ADD COLUMN IF NOT EXISTS pdf_original_filename TEXT;
ALTER TABLE public.consent_templates ADD COLUMN IF NOT EXISTS pdf_storage_path TEXT;
ALTER TABLE public.consent_templates ADD COLUMN IF NOT EXISTS sort_order INT NOT NULL DEFAULT 0;
ALTER TABLE public.consent_templates ADD COLUMN IF NOT EXISTS template_type TEXT NOT NULL DEFAULT 'html';

-- Table: contact_messages (3 columns)
ALTER TABLE public.contact_messages ADD COLUMN IF NOT EXISTS consented_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE public.contact_messages ADD COLUMN IF NOT EXISTS privacy_accepted BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE public.contact_messages ADD COLUMN IF NOT EXISTS terms_accepted BOOLEAN NOT NULL DEFAULT false;

-- Table: cost_centers (2 columns)
ALTER TABLE public.cost_centers ADD COLUMN IF NOT EXISTS color text not null default '#6366f1';
ALTER TABLE public.cost_centers ADD COLUMN IF NOT EXISTS updated_at timestamptz not null default now();

-- Table: dental_images (10 columns)
ALTER TABLE public.dental_images ADD COLUMN IF NOT EXISTS appointment_id UUID REFERENCES appointments(id) ON DELETE SET NULL;
ALTER TABLE public.dental_images ADD COLUMN IF NOT EXISTS client_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.dental_images ADD COLUMN IF NOT EXISTS clinical_notes TEXT;
ALTER TABLE public.dental_images ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.dental_images ADD COLUMN IF NOT EXISTS file_path TEXT NOT NULL;
ALTER TABLE public.dental_images ADD COLUMN IF NOT EXISTS file_size INTEGER;
ALTER TABLE public.dental_images ADD COLUMN IF NOT EXISTS medical_record_id UUID REFERENCES medical_records(id) ON DELETE SET NULL;
ALTER TABLE public.dental_images ADD COLUMN IF NOT EXISTS mime_type TEXT;
ALTER TABLE public.dental_images ADD COLUMN IF NOT EXISTS professional_id UUID REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.dental_images ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- Table: discount_coupons (3 columns)
ALTER TABLE public.discount_coupons ADD COLUMN IF NOT EXISTS service_id uuid        REFERENCES public.procedures(id) ON DELETE SET NULL;
ALTER TABLE public.discount_coupons ADD COLUMN IF NOT EXISTS valid_from date;
ALTER TABLE public.discount_coupons ADD COLUMN IF NOT EXISTS value numeric(10,2) NOT NULL;

-- Table: exam_results (14 columns)
ALTER TABLE public.exam_results ADD COLUMN IF NOT EXISTS appointment_id UUID REFERENCES public.appointments(id) ON DELETE SET NULL;
ALTER TABLE public.exam_results ADD COLUMN IF NOT EXISTS client_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.exam_results ADD COLUMN IF NOT EXISTS exam_name TEXT NOT NULL;
ALTER TABLE public.exam_results ADD COLUMN IF NOT EXISTS file_name TEXT;
ALTER TABLE public.exam_results ADD COLUMN IF NOT EXISTS interpretation TEXT;
ALTER TABLE public.exam_results ADD COLUMN IF NOT EXISTS lab_name TEXT;
ALTER TABLE public.exam_results ADD COLUMN IF NOT EXISTS medical_record_id UUID REFERENCES public.medical_records(id) ON DELETE SET NULL;
ALTER TABLE public.exam_results ADD COLUMN IF NOT EXISTS performed_at DATE;
ALTER TABLE public.exam_results ADD COLUMN IF NOT EXISTS priority TEXT NOT NULL DEFAULT 'normal';
ALTER TABLE public.exam_results ADD COLUMN IF NOT EXISTS reference_values TEXT;
ALTER TABLE public.exam_results ADD COLUMN IF NOT EXISTS requested_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL;
ALTER TABLE public.exam_results ADD COLUMN IF NOT EXISTS result_text TEXT;
ALTER TABLE public.exam_results ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'manual';
ALTER TABLE public.exam_results ADD COLUMN IF NOT EXISTS tuss_code TEXT;

-- Table: financial_transactions (3 columns)
ALTER TABLE public.financial_transactions ADD COLUMN IF NOT EXISTS commission_payment_id uuid references public.commission_payments(id) on delete set null;
ALTER TABLE public.financial_transactions ADD COLUMN IF NOT EXISTS product_id UUID NULL REFERENCES public.products(id) ON DELETE SET NULL;
ALTER TABLE public.financial_transactions ADD COLUMN IF NOT EXISTS salary_payment_id UUID REFERENCES public.salary_payments(id) ON DELETE SET NULL;

-- Table: goal_achievements (1 columns)
ALTER TABLE public.goal_achievements ADD COLUMN IF NOT EXISTS professional_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE;

-- Table: goal_suggestions (7 columns)
ALTER TABLE public.goal_suggestions ADD COLUMN IF NOT EXISTS created_goal_id UUID REFERENCES public.goals(id) ON DELETE SET NULL;
ALTER TABLE public.goal_suggestions ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE public.goal_suggestions ADD COLUMN IF NOT EXISTS period public.goal_period NOT NULL DEFAULT 'monthly';
ALTER TABLE public.goal_suggestions ADD COLUMN IF NOT EXISTS professional_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE;
ALTER TABLE public.goal_suggestions ADD COLUMN IF NOT EXISTS rejection_reason TEXT;
ALTER TABLE public.goal_suggestions ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ;
ALTER TABLE public.goal_suggestions ADD COLUMN IF NOT EXISTS reviewed_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL;

-- Table: goal_templates (3 columns)
ALTER TABLE public.goal_templates ADD COLUMN IF NOT EXISTS name TEXT NOT NULL;
ALTER TABLE public.goal_templates ADD COLUMN IF NOT EXISTS period public.goal_period NOT NULL DEFAULT 'monthly';
ALTER TABLE public.goal_templates ADD COLUMN IF NOT EXISTS target_value DECIMAL(15,2) NOT NULL;

-- Table: goals (6 columns)
ALTER TABLE public.goals ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE public.goals ADD COLUMN IF NOT EXISTS name TEXT NOT NULL;
ALTER TABLE public.goals ADD COLUMN IF NOT EXISTS period public.goal_period NOT NULL DEFAULT 'monthly';
ALTER TABLE public.goals ADD COLUMN IF NOT EXISTS product_id UUID REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.goals ADD COLUMN IF NOT EXISTS service_category_id UUID REFERENCES public.service_categories(id) ON DELETE SET NULL;
ALTER TABLE public.goals ADD COLUMN IF NOT EXISTS show_in_header BOOLEAN NOT NULL DEFAULT false;

-- Table: health_credits_rules (3 columns)
ALTER TABLE public.health_credits_rules ADD COLUMN IF NOT EXISTS description text DEFAULT '';
ALTER TABLE public.health_credits_rules ADD COLUMN IF NOT EXISTS expiry_days integer NOT NULL DEFAULT 365;
ALTER TABLE public.health_credits_rules ADD COLUMN IF NOT EXISTS max_per_day integer DEFAULT NULL;

-- Table: health_credits_transactions (1 columns)
ALTER TABLE public.health_credits_transactions ADD COLUMN IF NOT EXISTS expires_at timestamptz DEFAULT NULL;

-- Table: hl7_connections (9 columns)
ALTER TABLE public.hl7_connections ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES profiles(id);
ALTER TABLE public.hl7_connections ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE public.hl7_connections ADD COLUMN IF NOT EXISTS last_connected_at TIMESTAMPTZ;
ALTER TABLE public.hl7_connections ADD COLUMN IF NOT EXISTS last_error TEXT;
ALTER TABLE public.hl7_connections ADD COLUMN IF NOT EXISTS receiving_application TEXT;
ALTER TABLE public.hl7_connections ADD COLUMN IF NOT EXISTS receiving_facility TEXT;
ALTER TABLE public.hl7_connections ADD COLUMN IF NOT EXISTS remote_port INTEGER CHECK (remote_port > 0 AND remote_port < 65536);
ALTER TABLE public.hl7_connections ADD COLUMN IF NOT EXISTS sending_facility TEXT;
ALTER TABLE public.hl7_connections ADD COLUMN IF NOT EXISTS webhook_secret TEXT;

-- Table: hl7_field_mappings (4 columns)
ALTER TABLE public.hl7_field_mappings ADD COLUMN IF NOT EXISTS component_index INTEGER DEFAULT 0;
ALTER TABLE public.hl7_field_mappings ADD COLUMN IF NOT EXISTS default_value TEXT;
ALTER TABLE public.hl7_field_mappings ADD COLUMN IF NOT EXISTS field_index INTEGER NOT NULL;
ALTER TABLE public.hl7_field_mappings ADD COLUMN IF NOT EXISTS target_column TEXT NOT NULL;

-- Table: hl7_message_log (9 columns)
ALTER TABLE public.hl7_message_log ADD COLUMN IF NOT EXISTS ack_message TEXT;
ALTER TABLE public.hl7_message_log ADD COLUMN IF NOT EXISTS acknowledged_at TIMESTAMPTZ;
ALTER TABLE public.hl7_message_log ADD COLUMN IF NOT EXISTS appointment_id UUID REFERENCES appointments(id) ON DELETE SET NULL;
ALTER TABLE public.hl7_message_log ADD COLUMN IF NOT EXISTS error_message TEXT;
ALTER TABLE public.hl7_message_log ADD COLUMN IF NOT EXISTS exam_result_id UUID REFERENCES exam_results(id) ON DELETE SET NULL;
ALTER TABLE public.hl7_message_log ADD COLUMN IF NOT EXISTS message_control_id TEXT;
ALTER TABLE public.hl7_message_log ADD COLUMN IF NOT EXISTS next_retry_at TIMESTAMPTZ;
ALTER TABLE public.hl7_message_log ADD COLUMN IF NOT EXISTS parsed_data JSONB;
ALTER TABLE public.hl7_message_log ADD COLUMN IF NOT EXISTS processed_at TIMESTAMPTZ;

-- Table: insurance_plans (5 columns)
ALTER TABLE public.insurance_plans ADD COLUMN IF NOT EXISTS contact_email TEXT;
ALTER TABLE public.insurance_plans ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.insurance_plans ADD COLUMN IF NOT EXISTS reimbursement_days INTEGER DEFAULT 30;
ALTER TABLE public.insurance_plans ADD COLUMN IF NOT EXISTS requires_authorization BOOLEAN DEFAULT FALSE;
ALTER TABLE public.insurance_plans ADD COLUMN IF NOT EXISTS tiss_version TEXT;

-- Table: internal_messages (1 columns)
ALTER TABLE public.internal_messages ADD COLUMN IF NOT EXISTS channel_id UUID REFERENCES public.chat_channels(id) ON DELETE CASCADE;

-- Table: lgpd_data_requests (9 columns)
ALTER TABLE public.lgpd_data_requests ADD COLUMN IF NOT EXISTS assigned_admin_user_id UUID;
ALTER TABLE public.lgpd_data_requests ADD COLUMN IF NOT EXISTS due_at TIMESTAMPTZ;
ALTER TABLE public.lgpd_data_requests ADD COLUMN IF NOT EXISTS request_details TEXT;
ALTER TABLE public.lgpd_data_requests ADD COLUMN IF NOT EXISTS requester_email TEXT;
ALTER TABLE public.lgpd_data_requests ADD COLUMN IF NOT EXISTS requester_user_id UUID NOT NULL;
ALTER TABLE public.lgpd_data_requests ADD COLUMN IF NOT EXISTS resolution_notes TEXT;
ALTER TABLE public.lgpd_data_requests ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMPTZ;
ALTER TABLE public.lgpd_data_requests ADD COLUMN IF NOT EXISTS sla_days INTEGER NOT NULL DEFAULT 15;
ALTER TABLE public.lgpd_data_requests ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

-- Table: lgpd_retention_policies (7 columns)
ALTER TABLE public.lgpd_retention_policies ADD COLUMN IF NOT EXISTS audit_log_retention_days INTEGER NOT NULL DEFAULT 730 CHECK (audit_log_retention_days BETWEEN 30 AND 3650);
ALTER TABLE public.lgpd_retention_policies ADD COLUMN IF NOT EXISTS auto_cleanup_enabled BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE public.lgpd_retention_policies ADD COLUMN IF NOT EXISTS client_data_retention_days INTEGER NOT NULL DEFAULT 1825 CHECK (client_data_retention_days BETWEEN 30 AND 7300);
ALTER TABLE public.lgpd_retention_policies ADD COLUMN IF NOT EXISTS created_by UUID;
ALTER TABLE public.lgpd_retention_policies ADD COLUMN IF NOT EXISTS financial_data_retention_days INTEGER NOT NULL DEFAULT 3650 CHECK (financial_data_retention_days BETWEEN 365 AND 7300);
ALTER TABLE public.lgpd_retention_policies ADD COLUMN IF NOT EXISTS last_reviewed_at TIMESTAMPTZ;
ALTER TABLE public.lgpd_retention_policies ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

-- Table: loyalty_tiers (3 columns)
ALTER TABLE public.loyalty_tiers ADD COLUMN IF NOT EXISTS color text        NOT NULL DEFAULT '#6b7280';
ALTER TABLE public.loyalty_tiers ADD COLUMN IF NOT EXISTS discount_percent numeric(5,2) NOT NULL DEFAULT 0;
ALTER TABLE public.loyalty_tiers ADD COLUMN IF NOT EXISTS icon text        NOT NULL DEFAULT '🥉';

-- Table: medical_certificates (7 columns)
ALTER TABLE public.medical_certificates ADD COLUMN IF NOT EXISTS appointment_id UUID REFERENCES public.appointments(id) ON DELETE SET NULL;
ALTER TABLE public.medical_certificates ADD COLUMN IF NOT EXISTS client_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.medical_certificates ADD COLUMN IF NOT EXISTS digital_signature TEXT;
ALTER TABLE public.medical_certificates ADD COLUMN IF NOT EXISTS issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.medical_certificates ADD COLUMN IF NOT EXISTS medical_record_id UUID REFERENCES public.medical_records(id) ON DELETE SET NULL;
ALTER TABLE public.medical_certificates ADD COLUMN IF NOT EXISTS printed_at TIMESTAMPTZ;
ALTER TABLE public.medical_certificates ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- Table: medical_record_versions (4 columns)
ALTER TABLE public.medical_record_versions ADD COLUMN IF NOT EXISTS change_reason TEXT;
ALTER TABLE public.medical_record_versions ADD COLUMN IF NOT EXISTS changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.medical_record_versions ADD COLUMN IF NOT EXISTS digital_hash TEXT;
ALTER TABLE public.medical_record_versions ADD COLUMN IF NOT EXISTS snapshot JSONB NOT NULL;

-- Table: medical_records (19 columns)
ALTER TABLE public.medical_records ADD COLUMN IF NOT EXISTS anamnesis TEXT;
ALTER TABLE public.medical_records ADD COLUMN IF NOT EXISTS blood_pressure_systolic INTEGER;
ALTER TABLE public.medical_records ADD COLUMN IF NOT EXISTS chief_complaint TEXT;
ALTER TABLE public.medical_records ADD COLUMN IF NOT EXISTS cid_code TEXT;
ALTER TABLE public.medical_records ADD COLUMN IF NOT EXISTS client_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.medical_records ADD COLUMN IF NOT EXISTS custom_fields JSONB DEFAULT '{}';
ALTER TABLE public.medical_records ADD COLUMN IF NOT EXISTS diagnosis TEXT;
ALTER TABLE public.medical_records ADD COLUMN IF NOT EXISTS digital_hash TEXT;
ALTER TABLE public.medical_records ADD COLUMN IF NOT EXISTS is_confidential BOOLEAN DEFAULT FALSE;
ALTER TABLE public.medical_records ADD COLUMN IF NOT EXISTS physical_exam TEXT;
ALTER TABLE public.medical_records ADD COLUMN IF NOT EXISTS prescriptions TEXT;
ALTER TABLE public.medical_records ADD COLUMN IF NOT EXISTS record_date DATE NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE public.medical_records ADD COLUMN IF NOT EXISTS return_days INTEGER;
ALTER TABLE public.medical_records ADD COLUMN IF NOT EXISTS return_reason TEXT;
ALTER TABLE public.medical_records ADD COLUMN IF NOT EXISTS return_reminder_id UUID REFERENCES return_reminders(id) ON DELETE SET NULL;
ALTER TABLE public.medical_records ADD COLUMN IF NOT EXISTS specialty_id UUID REFERENCES public.specialties(id) ON DELETE SET NULL;
ALTER TABLE public.medical_records ADD COLUMN IF NOT EXISTS template_id UUID REFERENCES public.record_field_templates(id) ON DELETE SET NULL;
ALTER TABLE public.medical_records ADD COLUMN IF NOT EXISTS treatment_plan TEXT;
ALTER TABLE public.medical_records ADD COLUMN IF NOT EXISTS triage_id UUID REFERENCES public.triage_records(id) ON DELETE SET NULL;

-- Table: message_templates (4 columns)
ALTER TABLE public.message_templates ADD COLUMN IF NOT EXISTS category text;
ALTER TABLE public.message_templates ADD COLUMN IF NOT EXISTS content text NOT NULL CHECK (char_length(content) <= 2000);
ALTER TABLE public.message_templates ADD COLUMN IF NOT EXISTS title text NOT NULL;
ALTER TABLE public.message_templates ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

-- Table: nfse_invoices (15 columns)
ALTER TABLE public.nfse_invoices ADD COLUMN IF NOT EXISTS borrower_document TEXT;
ALTER TABLE public.nfse_invoices ADD COLUMN IF NOT EXISTS borrower_email TEXT;
ALTER TABLE public.nfse_invoices ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ;
ALTER TABLE public.nfse_invoices ADD COLUMN IF NOT EXISTS check_code TEXT;
ALTER TABLE public.nfse_invoices ADD COLUMN IF NOT EXISTS client_id UUID REFERENCES public.patients(id) ON DELETE SET NULL;
ALTER TABLE public.nfse_invoices ADD COLUMN IF NOT EXISTS description TEXT NOT NULL;
ALTER TABLE public.nfse_invoices ADD COLUMN IF NOT EXISTS iss_amount DECIMAL(12,2);
ALTER TABLE public.nfse_invoices ADD COLUMN IF NOT EXISTS iss_rate DECIMAL(5,4);
ALTER TABLE public.nfse_invoices ADD COLUMN IF NOT EXISTS nfeio_status TEXT NOT NULL DEFAULT 'pending';
ALTER TABLE public.nfse_invoices ADD COLUMN IF NOT EXISTS rps_number INTEGER;
ALTER TABLE public.nfse_invoices ADD COLUMN IF NOT EXISTS rps_serial TEXT;
ALTER TABLE public.nfse_invoices ADD COLUMN IF NOT EXISTS services_amount DECIMAL(12,2) NOT NULL;
ALTER TABLE public.nfse_invoices ADD COLUMN IF NOT EXISTS total_amount DECIMAL(12,2) NOT NULL;
ALTER TABLE public.nfse_invoices ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.nfse_invoices ADD COLUMN IF NOT EXISTS xml_url TEXT;

-- Table: notifications (1 columns)
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS body TEXT;

-- Table: nps_responses (4 columns)
ALTER TABLE public.nps_responses ADD COLUMN IF NOT EXISTS appointment_id uuid references public.appointments(id) on delete set null;
ALTER TABLE public.nps_responses ADD COLUMN IF NOT EXISTS client_id uuid REFERENCES public.patients(id) on delete set null;
ALTER TABLE public.nps_responses ADD COLUMN IF NOT EXISTS responded_at timestamptz;
ALTER TABLE public.nps_responses ADD COLUMN IF NOT EXISTS token uuid unique not null default gen_random_uuid();

-- Table: nursing_evolutions (1 columns)
ALTER TABLE public.nursing_evolutions ADD COLUMN IF NOT EXISTS medical_record_id UUID REFERENCES public.medical_records(id) ON DELETE SET NULL;

-- Table: odontogram_annotations (1 columns)
ALTER TABLE public.odontogram_annotations ADD COLUMN IF NOT EXISTS ou NUMBER = nota específica do dente
  created_by      UUID REFERENCES public.profiles(id);

-- Table: odontogram_teeth (3 columns)
ALTER TABLE public.odontogram_teeth ADD COLUMN IF NOT EXISTS attachment_urls TEXT[] DEFAULT '{}';
ALTER TABLE public.odontogram_teeth ADD COLUMN IF NOT EXISTS mobility_grade INTEGER DEFAULT NULL;
ALTER TABLE public.odontogram_teeth ADD COLUMN IF NOT EXISTS priority TEXT DEFAULT 'normal';

-- Table: odontogram_tooth_surfaces (2 columns)
ALTER TABLE public.odontogram_tooth_surfaces ADD COLUMN IF NOT EXISTS material TEXT;
ALTER TABLE public.odontogram_tooth_surfaces ADD COLUMN IF NOT EXISTS odontogram_tooth_id UUID NOT NULL REFERENCES public.odontogram_teeth(id) ON DELETE CASCADE;

-- Table: odontograms (6 columns)
ALTER TABLE public.odontograms ADD COLUMN IF NOT EXISTS appointment_id UUID REFERENCES public.appointments(id) ON DELETE SET NULL;
ALTER TABLE public.odontograms ADD COLUMN IF NOT EXISTS client_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.odontograms ADD COLUMN IF NOT EXISTS dentition_type TEXT NOT NULL DEFAULT 'permanent';
ALTER TABLE public.odontograms ADD COLUMN IF NOT EXISTS signed_at TIMESTAMPTZ;
ALTER TABLE public.odontograms ADD COLUMN IF NOT EXISTS signed_by_crm TEXT;
ALTER TABLE public.odontograms ADD COLUMN IF NOT EXISTS signed_by_name TEXT;

-- Table: ona_indicators (25 columns)
ALTER TABLE public.ona_indicators ADD COLUMN IF NOT EXISTS calculado_por TEXT DEFAULT 'SISTEMA';
ALTER TABLE public.ona_indicators ADD COLUMN IF NOT EXISTS campos_obrigatorios_faltantes JSONB;
ALTER TABLE public.ona_indicators ADD COLUMN IF NOT EXISTS eventos_por_severidade JSONB;
ALTER TABLE public.ona_indicators ADD COLUMN IF NOT EXISTS horas_disponiveis NUMERIC(10,2);
ALTER TABLE public.ona_indicators ADD COLUMN IF NOT EXISTS horas_ocupadas NUMERIC(10,2);
ALTER TABLE public.ona_indicators ADD COLUMN IF NOT EXISTS mensal -- 22.2 Tempo médio de espera (minutos)
  tempo_espera_medio NUMERIC(10,2);
ALTER TABLE public.ona_indicators ADD COLUMN IF NOT EXISTS nps_detratores INTEGER;
ALTER TABLE public.ona_indicators ADD COLUMN IF NOT EXISTS nps_neutros INTEGER;
ALTER TABLE public.ona_indicators ADD COLUMN IF NOT EXISTS nps_promotores INTEGER;
ALTER TABLE public.ona_indicators ADD COLUMN IF NOT EXISTS ocupacao_por_sala JSONB;
ALTER TABLE public.ona_indicators ADD COLUMN IF NOT EXISTS periodo_fim DATE NOT NULL;
ALTER TABLE public.ona_indicators ADD COLUMN IF NOT EXISTS prontuarios_completos INTEGER;
ALTER TABLE public.ona_indicators ADD COLUMN IF NOT EXISTS taxa_noshow NUMERIC(5,2);
ALTER TABLE public.ona_indicators ADD COLUMN IF NOT EXISTS tempo_espera_max NUMERIC(10,2);
ALTER TABLE public.ona_indicators ADD COLUMN IF NOT EXISTS tempo_espera_min NUMERIC(10,2);
ALTER TABLE public.ona_indicators ADD COLUMN IF NOT EXISTS tempo_espera_p90 NUMERIC(10,2);
ALTER TABLE public.ona_indicators ADD COLUMN IF NOT EXISTS tipo_periodo TEXT NOT NULL DEFAULT 'MENSAL';
ALTER TABLE public.ona_indicators ADD COLUMN IF NOT EXISTS total_agendamentos INTEGER;
ALTER TABLE public.ona_indicators ADD COLUMN IF NOT EXISTS total_atendimentos_periodo INTEGER;
ALTER TABLE public.ona_indicators ADD COLUMN IF NOT EXISTS total_cancelados INTEGER;
ALTER TABLE public.ona_indicators ADD COLUMN IF NOT EXISTS total_noshow INTEGER;
ALTER TABLE public.ona_indicators ADD COLUMN IF NOT EXISTS total_prontuarios INTEGER;
ALTER TABLE public.ona_indicators ADD COLUMN IF NOT EXISTS total_realizados INTEGER;
ALTER TABLE public.ona_indicators ADD COLUMN IF NOT EXISTS total_respostas_nps INTEGER;
ALTER TABLE public.ona_indicators ADD COLUMN IF NOT EXISTS total_retornos_7dias INTEGER;

-- Table: order_items (7 columns)
ALTER TABLE public.order_items ADD COLUMN IF NOT EXISTS kind public.order_item_kind NOT NULL;
ALTER TABLE public.order_items ADD COLUMN IF NOT EXISTS product_id uuid NULL REFERENCES public.products(id);
ALTER TABLE public.order_items ADD COLUMN IF NOT EXISTS professional_id uuid NULL REFERENCES public.profiles(id);
ALTER TABLE public.order_items ADD COLUMN IF NOT EXISTS service_id uuid NULL REFERENCES public.procedures(id);
ALTER TABLE public.order_items ADD COLUMN IF NOT EXISTS total_cost_snapshot numeric(12,4);
ALTER TABLE public.order_items ADD COLUMN IF NOT EXISTS total_price numeric(12,2) NOT NULL;
ALTER TABLE public.order_items ADD COLUMN IF NOT EXISTS unit_cost_snapshot numeric(12,4);

-- Table: orders (8 columns)
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS applied_voucher_id uuid REFERENCES vouchers(id) ON DELETE SET NULL;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS client_id uuid NULL REFERENCES public.patients(id);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS created_by uuid NULL;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS discount_amount numeric(12,2) NOT NULL DEFAULT 0;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS paid_at timestamptz;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS professional_id uuid NULL REFERENCES public.profiles(id);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS subtotal_amount numeric(12,2) NOT NULL DEFAULT 0;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS total_amount numeric(12,2) NOT NULL DEFAULT 0;

-- Table: patient_achievements (3 columns)
ALTER TABLE public.patient_achievements ADD COLUMN IF NOT EXISTS achieved_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.patient_achievements ADD COLUMN IF NOT EXISTS achievement_name text NOT NULL;
ALTER TABLE public.patient_achievements ADD COLUMN IF NOT EXISTS patient_user_id uuid NOT NULL;

-- Table: patient_calls (2 columns)
ALTER TABLE public.patient_calls ADD COLUMN IF NOT EXISTS is_triaged BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.patient_calls ADD COLUMN IF NOT EXISTS triage_priority TEXT;

-- Table: patient_consents (9 columns)
ALTER TABLE public.patient_consents ADD COLUMN IF NOT EXISTS client_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.patient_consents ADD COLUMN IF NOT EXISTS document_hash TEXT;
ALTER TABLE public.patient_consents ADD COLUMN IF NOT EXISTS facial_photo_path TEXT;
ALTER TABLE public.patient_consents ADD COLUMN IF NOT EXISTS manual_signature_path TEXT;
ALTER TABLE public.patient_consents ADD COLUMN IF NOT EXISTS patient_user_id UUID NOT NULL;
ALTER TABLE public.patient_consents ADD COLUMN IF NOT EXISTS sealed_at TIMESTAMPTZ;
ALTER TABLE public.patient_consents ADD COLUMN IF NOT EXISTS sealed_pdf_hash TEXT;
ALTER TABLE public.patient_consents ADD COLUMN IF NOT EXISTS sealed_pdf_path TEXT;
ALTER TABLE public.patient_consents ADD COLUMN IF NOT EXISTS signature_method TEXT;

-- Table: patient_dependents (4 columns)
ALTER TABLE public.patient_dependents ADD COLUMN IF NOT EXISTS dependent_client_id uuid NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.patient_dependents ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;
ALTER TABLE public.patient_dependents ADD COLUMN IF NOT EXISTS parent_client_id uuid NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.patient_dependents ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

-- Table: patient_invoices (8 columns)
ALTER TABLE public.patient_invoices ADD COLUMN IF NOT EXISTS appointment_id uuid REFERENCES public.appointments(id) ON DELETE SET NULL;
ALTER TABLE public.patient_invoices ADD COLUMN IF NOT EXISTS client_id uuid NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.patient_invoices ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.patient_invoices ADD COLUMN IF NOT EXISTS paid_amount numeric(12,2);
ALTER TABLE public.patient_invoices ADD COLUMN IF NOT EXISTS payment_gateway text;
ALTER TABLE public.patient_invoices ADD COLUMN IF NOT EXISTS payment_gateway_id text;
ALTER TABLE public.patient_invoices ADD COLUMN IF NOT EXISTS payment_method text;
ALTER TABLE public.patient_invoices ADD COLUMN IF NOT EXISTS payment_url text;

-- Table: patient_messages (3 columns)
ALTER TABLE public.patient_messages ADD COLUMN IF NOT EXISTS sender_name text;
ALTER TABLE public.patient_messages ADD COLUMN IF NOT EXISTS sender_type text NOT NULL CHECK (sender_type IN ('patient', 'clinic'));
ALTER TABLE public.patient_messages ADD COLUMN IF NOT EXISTS sender_user_id uuid;

-- Table: patient_notifications (2 columns)
ALTER TABLE public.patient_notifications ADD COLUMN IF NOT EXISTS body TEXT;
ALTER TABLE public.patient_notifications ADD COLUMN IF NOT EXISTS user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE;

-- Table: patient_payments (5 columns)
ALTER TABLE public.patient_payments ADD COLUMN IF NOT EXISTS gateway_transaction_id text;
ALTER TABLE public.patient_payments ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.patient_payments ADD COLUMN IF NOT EXISTS paid_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.patient_payments ADD COLUMN IF NOT EXISTS payment_gateway text;
ALTER TABLE public.patient_payments ADD COLUMN IF NOT EXISTS receipt_url text;

-- Table: patient_profiles (2 columns)
ALTER TABLE public.patient_profiles ADD COLUMN IF NOT EXISTS client_id uuid NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.patient_profiles ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;

-- Table: patient_proms (1 columns)
ALTER TABLE public.patient_proms ADD COLUMN IF NOT EXISTS questionnaire text NOT NULL DEFAULT 'general';

-- Table: patient_vaccinations (8 columns)
ALTER TABLE public.patient_vaccinations ADD COLUMN IF NOT EXISTS administered_by text;
ALTER TABLE public.patient_vaccinations ADD COLUMN IF NOT EXISTS batch_number text;
ALTER TABLE public.patient_vaccinations ADD COLUMN IF NOT EXISTS client_id uuid NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.patient_vaccinations ADD COLUMN IF NOT EXISTS dose_number integer;
ALTER TABLE public.patient_vaccinations ADD COLUMN IF NOT EXISTS location text;
ALTER TABLE public.patient_vaccinations ADD COLUMN IF NOT EXISTS next_dose_date date;
ALTER TABLE public.patient_vaccinations ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.patient_vaccinations ADD COLUMN IF NOT EXISTS vaccine_code text;

-- Table: payment_methods (2 columns)
ALTER TABLE public.payment_methods ADD COLUMN IF NOT EXISTS code text NOT NULL;
ALTER TABLE public.payment_methods ADD COLUMN IF NOT EXISTS sort_order integer NOT NULL DEFAULT 0;

-- Table: payments (2 columns)
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS paid_at timestamptz NULL;
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS reference text NULL;

-- Table: periogram_measurements (1 columns)
ALTER TABLE public.periogram_measurements ADD COLUMN IF NOT EXISTS clinical_attachment_level NUMERIC(4,1);

-- Table: periograms (6 columns)
ALTER TABLE public.periograms ADD COLUMN IF NOT EXISTS appointment_id UUID REFERENCES appointments(id) ON DELETE SET NULL;
ALTER TABLE public.periograms ADD COLUMN IF NOT EXISTS client_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.periograms ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.periograms ADD COLUMN IF NOT EXISTS exam_date DATE NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE public.periograms ADD COLUMN IF NOT EXISTS medical_record_id UUID REFERENCES medical_records(id) ON DELETE SET NULL;
ALTER TABLE public.periograms ADD COLUMN IF NOT EXISTS periodontite leve/moderada/severa
  risk_classification TEXT CHECK (risk_classification IN ('baixo', 'moderado', 'alto'));

-- Table: permission_overrides (1 columns)
ALTER TABLE public.permission_overrides ADD COLUMN IF NOT EXISTS unit_id UUID REFERENCES public.clinic_units(id) ON DELETE CASCADE;

-- Table: points_ledger (5 columns)
ALTER TABLE public.points_ledger ADD COLUMN IF NOT EXISTS client_id uuid        NOT NULL REFERENCES public.patients(id)        ON DELETE CASCADE;
ALTER TABLE public.points_ledger ADD COLUMN IF NOT EXISTS delta integer     NOT NULL;
ALTER TABLE public.points_ledger ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.points_ledger ADD COLUMN IF NOT EXISTS reason text        NOT NULL CHECK (reason IN ('earn','redeem','adjust','expire'));
ALTER TABLE public.points_ledger ADD COLUMN IF NOT EXISTS ref_id uuid;

-- Table: points_wallets (1 columns)
ALTER TABLE public.points_wallets ADD COLUMN IF NOT EXISTS client_id uuid        NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE;

-- Table: prescriptions (10 columns)
ALTER TABLE public.prescriptions ADD COLUMN IF NOT EXISTS client_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.prescriptions ADD COLUMN IF NOT EXISTS digital_signature TEXT;
ALTER TABLE public.prescriptions ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;
ALTER TABLE public.prescriptions ADD COLUMN IF NOT EXISTS instructions TEXT;
ALTER TABLE public.prescriptions ADD COLUMN IF NOT EXISTS issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.prescriptions ADD COLUMN IF NOT EXISTS medical_record_id UUID REFERENCES public.medical_records(id) ON DELETE SET NULL;
ALTER TABLE public.prescriptions ADD COLUMN IF NOT EXISTS prescription_type TEXT NOT NULL DEFAULT 'simples'
                      CHECK (prescription_type IN ('simples','especial_b','especial_a','antimicrobiano'));
ALTER TABLE public.prescriptions ADD COLUMN IF NOT EXISTS printed_at TIMESTAMPTZ;
ALTER TABLE public.prescriptions ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'ativo'
                      CHECK (status IN ('ativo','expirado','cancelado'));
ALTER TABLE public.prescriptions ADD COLUMN IF NOT EXISTS validity_days INTEGER DEFAULT 30;

-- Table: professional_commissions (7 columns)
ALTER TABLE public.professional_commissions ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES public.profiles(user_id) ON DELETE SET NULL;
ALTER TABLE public.professional_commissions ADD COLUMN IF NOT EXISTS default_payment_method TEXT;
ALTER TABLE public.professional_commissions ADD COLUMN IF NOT EXISTS payment_type TEXT DEFAULT 'commission';
ALTER TABLE public.professional_commissions ADD COLUMN IF NOT EXISTS salary_amount DECIMAL(10,2);
ALTER TABLE public.professional_commissions ADD COLUMN IF NOT EXISTS salary_payment_day INTEGER;
ALTER TABLE public.professional_commissions ADD COLUMN IF NOT EXISTS user_id UUID NOT NULL;
ALTER TABLE public.professional_commissions ADD COLUMN IF NOT EXISTS value NUMERIC NOT NULL DEFAULT 0;

-- Table: professional_working_hours (1 columns)
ALTER TABLE public.professional_working_hours ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

-- Table: profiles (6 columns)
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS cns VARCHAR(15);
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS default_unit_id UUID REFERENCES public.clinic_units(id) ON DELETE SET NULL;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS is_readonly BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS patient_bookable boolean NOT NULL DEFAULT false;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS show_gamification_popups boolean DEFAULT true;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS show_goals_progress_in_header BOOLEAN NOT NULL DEFAULT true;

-- Table: purchase_items (4 columns)
ALTER TABLE public.purchase_items ADD COLUMN IF NOT EXISTS line_total numeric not null default 0;
ALTER TABLE public.purchase_items ADD COLUMN IF NOT EXISTS prev_cost numeric;
ALTER TABLE public.purchase_items ADD COLUMN IF NOT EXISTS prev_quantity integer;
ALTER TABLE public.purchase_items ADD COLUMN IF NOT EXISTS stock_movement_id uuid references public.stock_movements(id) on delete set null;

-- Table: purchases (8 columns)
ALTER TABLE public.purchases ADD COLUMN IF NOT EXISTS cancel_reason text;
ALTER TABLE public.purchases ADD COLUMN IF NOT EXISTS cancelled_at timestamptz;
ALTER TABLE public.purchases ADD COLUMN IF NOT EXISTS cancelled_by uuid;
ALTER TABLE public.purchases ADD COLUMN IF NOT EXISTS created_by uuid;
ALTER TABLE public.purchases ADD COLUMN IF NOT EXISTS financial_transaction_id uuid references public.financial_transactions(id) on delete set null;
ALTER TABLE public.purchases ADD COLUMN IF NOT EXISTS purchased_at timestamptz not null default now();
ALTER TABLE public.purchases ADD COLUMN IF NOT EXISTS purchased_with_company_cash boolean not null default false;
ALTER TABLE public.purchases ADD COLUMN IF NOT EXISTS total_amount numeric not null default 0;

-- Table: push_subscriptions (4 columns)
ALTER TABLE public.push_subscriptions ADD COLUMN IF NOT EXISTS notify_messages BOOLEAN DEFAULT true;
ALTER TABLE public.push_subscriptions ADD COLUMN IF NOT EXISTS notify_reminders BOOLEAN DEFAULT true;
ALTER TABLE public.push_subscriptions ADD COLUMN IF NOT EXISTS notify_triagem BOOLEAN DEFAULT true;
ALTER TABLE public.push_subscriptions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- Table: referrals (10 columns)
ALTER TABLE public.referrals ADD COLUMN IF NOT EXISTS appointment_id UUID REFERENCES public.appointments(id) ON DELETE SET NULL;
ALTER TABLE public.referrals ADD COLUMN IF NOT EXISTS client_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.referrals ADD COLUMN IF NOT EXISTS clinical_summary TEXT;
ALTER TABLE public.referrals ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;
ALTER TABLE public.referrals ADD COLUMN IF NOT EXISTS from_professional UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE;
ALTER TABLE public.referrals ADD COLUMN IF NOT EXISTS medical_record_id UUID REFERENCES public.medical_records(id) ON DELETE SET NULL;
ALTER TABLE public.referrals ADD COLUMN IF NOT EXISTS priority TEXT NOT NULL DEFAULT 'normal'
                      CHECK (priority IN ('normal','urgente','emergencia'));
ALTER TABLE public.referrals ADD COLUMN IF NOT EXISTS responded_at TIMESTAMPTZ;
ALTER TABLE public.referrals ADD COLUMN IF NOT EXISTS to_professional UUID REFERENCES public.profiles(id) ON DELETE SET NULL;
ALTER TABLE public.referrals ADD COLUMN IF NOT EXISTS to_specialty_id UUID REFERENCES public.specialties(id) ON DELETE SET NULL;

-- Table: return_reminders (1 columns)
ALTER TABLE public.return_reminders ADD COLUMN IF NOT EXISTS notified_at TIMESTAMPTZ;

-- Table: rnds_certificates (8 columns)
ALTER TABLE public.rnds_certificates ADD COLUMN IF NOT EXISTS issuer VARCHAR(255);
ALTER TABLE public.rnds_certificates ADD COLUMN IF NOT EXISTS name VARCHAR(255) NOT NULL;
ALTER TABLE public.rnds_certificates ADD COLUMN IF NOT EXISTS subject_cn VARCHAR(255);
ALTER TABLE public.rnds_certificates ADD COLUMN IF NOT EXISTS subject_cnpj VARCHAR(14);
ALTER TABLE public.rnds_certificates ADD COLUMN IF NOT EXISTS subject_cpf VARCHAR(11);
ALTER TABLE public.rnds_certificates ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.rnds_certificates ADD COLUMN IF NOT EXISTS valid_from TIMESTAMPTZ NOT NULL;
ALTER TABLE public.rnds_certificates ADD COLUMN IF NOT EXISTS valid_to TIMESTAMPTZ NOT NULL;

-- Table: rnds_submissions (14 columns)
ALTER TABLE public.rnds_submissions ADD COLUMN IF NOT EXISTS appointment_id UUID REFERENCES appointments(id) ON DELETE SET NULL;
ALTER TABLE public.rnds_submissions ADD COLUMN IF NOT EXISTS attempt_count INTEGER DEFAULT 0;
ALTER TABLE public.rnds_submissions ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES public.profiles(id);
ALTER TABLE public.rnds_submissions ADD COLUMN IF NOT EXISTS error_code VARCHAR(50);
ALTER TABLE public.rnds_submissions ADD COLUMN IF NOT EXISTS error_message TEXT;
ALTER TABLE public.rnds_submissions ADD COLUMN IF NOT EXISTS max_attempts INTEGER DEFAULT 3;
ALTER TABLE public.rnds_submissions ADD COLUMN IF NOT EXISTS medical_record_id UUID REFERENCES medical_records(id) ON DELETE SET NULL;
ALTER TABLE public.rnds_submissions ADD COLUMN IF NOT EXISTS next_retry_at TIMESTAMPTZ;
ALTER TABLE public.rnds_submissions ADD COLUMN IF NOT EXISTS patient_id UUID REFERENCES public.patients(id) ON DELETE SET NULL;
ALTER TABLE public.rnds_submissions ADD COLUMN IF NOT EXISTS processed_at TIMESTAMPTZ;
ALTER TABLE public.rnds_submissions ADD COLUMN IF NOT EXISTS rnds_protocol VARCHAR(100);
ALTER TABLE public.rnds_submissions ADD COLUMN IF NOT EXISTS rnds_response JSONB;
ALTER TABLE public.rnds_submissions ADD COLUMN IF NOT EXISTS scheduled_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.rnds_submissions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- Table: rnds_tokens (1 columns)
ALTER TABLE public.rnds_tokens ADD COLUMN IF NOT EXISTS scope TEXT;

-- Table: rooms (1 columns)
ALTER TABLE public.rooms ADD COLUMN IF NOT EXISTS capacity INTEGER DEFAULT 1;

-- Table: salary_payments (6 columns)
ALTER TABLE public.salary_payments ADD COLUMN IF NOT EXISTS days_in_month INTEGER CHECK (days_in_month IS NULL OR (days_in_month >= 28 AND days_in_month <= 31));
ALTER TABLE public.salary_payments ADD COLUMN IF NOT EXISTS days_worked INTEGER CHECK (days_worked IS NULL OR (days_worked >= 1 AND days_worked <= 31));
ALTER TABLE public.salary_payments ADD COLUMN IF NOT EXISTS etc -- Metadados
  paid_by UUID REFERENCES public.profiles(user_id) ON DELETE SET NULL;
ALTER TABLE public.salary_payments ADD COLUMN IF NOT EXISTS payment_reference TEXT;
ALTER TABLE public.salary_payments ADD COLUMN IF NOT EXISTS payment_year INTEGER NOT NULL CHECK (payment_year >= 2020);
ALTER TABLE public.salary_payments ADD COLUMN IF NOT EXISTS professional_commission_id UUID REFERENCES public.professional_commissions(id) ON DELETE SET NULL;

-- Table: schedule_blocks (1 columns)
ALTER TABLE public.schedule_blocks ADD COLUMN IF NOT EXISTS created_by uuid NULL;

-- Table: services (2 columns)
ALTER TABLE public.services ADD COLUMN IF NOT EXISTS patient_bookable boolean NOT NULL DEFAULT false;
ALTER TABLE public.services ADD COLUMN IF NOT EXISTS specialty_id UUID REFERENCES public.specialties(id);

-- Table: sngpc_estoque (15 columns)
ALTER TABLE public.sngpc_estoque ADD COLUMN IF NOT EXISTS data_entrada DATE NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE public.sngpc_estoque ADD COLUMN IF NOT EXISTS data_fabricacao DATE;
ALTER TABLE public.sngpc_estoque ADD COLUMN IF NOT EXISTS data_validade DATE NOT NULL;
ALTER TABLE public.sngpc_estoque ADD COLUMN IF NOT EXISTS fornecedor_id UUID REFERENCES suppliers(id);
ALTER TABLE public.sngpc_estoque ADD COLUMN IF NOT EXISTS lista TEXT NOT NULL CHECK (lista IN ('A1','A2','A3','B1','B2','C1','C2','C3','C4','C5'));
ALTER TABLE public.sngpc_estoque ADD COLUMN IF NOT EXISTS lote TEXT NOT NULL;
ALTER TABLE public.sngpc_estoque ADD COLUMN IF NOT EXISTS medicamento_codigo TEXT NOT NULL;
ALTER TABLE public.sngpc_estoque ADD COLUMN IF NOT EXISTS medicamento_nome TEXT NOT NULL;
ALTER TABLE public.sngpc_estoque ADD COLUMN IF NOT EXISTS nota_fiscal TEXT;
ALTER TABLE public.sngpc_estoque ADD COLUMN IF NOT EXISTS observacoes TEXT;
ALTER TABLE public.sngpc_estoque ADD COLUMN IF NOT EXISTS preco_unitario DECIMAL(10,2);
ALTER TABLE public.sngpc_estoque ADD COLUMN IF NOT EXISTS quantidade_atual INTEGER NOT NULL DEFAULT 0;
ALTER TABLE public.sngpc_estoque ADD COLUMN IF NOT EXISTS quantidade_inicial INTEGER NOT NULL;
ALTER TABLE public.sngpc_estoque ADD COLUMN IF NOT EXISTS unidade TEXT NOT NULL DEFAULT 'comprimido';
ALTER TABLE public.sngpc_estoque ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- Table: sngpc_movimentacoes (19 columns)
ALTER TABLE public.sngpc_movimentacoes ADD COLUMN IF NOT EXISTS comprador_endereco TEXT;
ALTER TABLE public.sngpc_movimentacoes ADD COLUMN IF NOT EXISTS comprador_parentesco TEXT;
ALTER TABLE public.sngpc_movimentacoes ADD COLUMN IF NOT EXISTS comprador_rg TEXT;
ALTER TABLE public.sngpc_movimentacoes ADD COLUMN IF NOT EXISTS comprador_telefone TEXT;
ALTER TABLE public.sngpc_movimentacoes ADD COLUMN IF NOT EXISTS data_movimentacao TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.sngpc_movimentacoes ADD COLUMN IF NOT EXISTS nota_fiscal TEXT;
ALTER TABLE public.sngpc_movimentacoes ADD COLUMN IF NOT EXISTS numero_boletim_ocorrencia TEXT;
ALTER TABLE public.sngpc_movimentacoes ADD COLUMN IF NOT EXISTS numero_receita TEXT;
ALTER TABLE public.sngpc_movimentacoes ADD COLUMN IF NOT EXISTS observacoes TEXT;
ALTER TABLE public.sngpc_movimentacoes ADD COLUMN IF NOT EXISTS paciente_cpf TEXT;
ALTER TABLE public.sngpc_movimentacoes ADD COLUMN IF NOT EXISTS paciente_nome TEXT;
ALTER TABLE public.sngpc_movimentacoes ADD COLUMN IF NOT EXISTS prescricao_id UUID;
ALTER TABLE public.sngpc_movimentacoes ADD COLUMN IF NOT EXISTS prescriptor_crm TEXT;
ALTER TABLE public.sngpc_movimentacoes ADD COLUMN IF NOT EXISTS prescriptor_nome TEXT;
ALTER TABLE public.sngpc_movimentacoes ADD COLUMN IF NOT EXISTS quantidade INTEGER NOT NULL;
ALTER TABLE public.sngpc_movimentacoes ADD COLUMN IF NOT EXISTS saldo_anterior INTEGER NOT NULL;
ALTER TABLE public.sngpc_movimentacoes ADD COLUMN IF NOT EXISTS saldo_posterior INTEGER NOT NULL;
ALTER TABLE public.sngpc_movimentacoes ADD COLUMN IF NOT EXISTS tipo_movimentacao TEXT NOT NULL CHECK (tipo_movimentacao IN (
    'ENTRADA_COMPRA',
    'ENTRADA_TRANSFERENCIA',
    'ENTRADA_DEVOLUCAO',
    'SAIDA_DISPENSACAO',
    'SAIDA_PERDA',
    'SAIDA_VENCIMENTO',
    'SAIDA_TRANSFERENCIA',
    'SAIDA_APREENSAO',
    'AJUSTE_INVENTARIO'
  ));
ALTER TABLE public.sngpc_movimentacoes ADD COLUMN IF NOT EXISTS usuario_nome TEXT NOT NULL;

-- Table: sngpc_transmissoes (12 columns)
ALTER TABLE public.sngpc_transmissoes ADD COLUMN IF NOT EXISTS data_envio TIMESTAMPTZ;
ALTER TABLE public.sngpc_transmissoes ADD COLUMN IF NOT EXISTS data_fim DATE NOT NULL;
ALTER TABLE public.sngpc_transmissoes ADD COLUMN IF NOT EXISTS data_validacao TIMESTAMPTZ;
ALTER TABLE public.sngpc_transmissoes ADD COLUMN IF NOT EXISTS enviado_por_cpf VARCHAR(14);
ALTER TABLE public.sngpc_transmissoes ADD COLUMN IF NOT EXISTS enviado_por_nome VARCHAR(200);
ALTER TABLE public.sngpc_transmissoes ADD COLUMN IF NOT EXISTS hash_anvisa VARCHAR(100);
ALTER TABLE public.sngpc_transmissoes ADD COLUMN IF NOT EXISTS motivo_retificacao TEXT;
ALTER TABLE public.sngpc_transmissoes ADD COLUMN IF NOT EXISTS total_medicamentos INTEGER DEFAULT 0;
ALTER TABLE public.sngpc_transmissoes ADD COLUMN IF NOT EXISTS total_saidas_perda INTEGER DEFAULT 0;
ALTER TABLE public.sngpc_transmissoes ADD COLUMN IF NOT EXISTS total_saidas_transferencia INTEGER DEFAULT 0;
ALTER TABLE public.sngpc_transmissoes ADD COLUMN IF NOT EXISTS total_saidas_venda INTEGER DEFAULT 0;
ALTER TABLE public.sngpc_transmissoes ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- Table: specialties (2 columns)
ALTER TABLE public.specialties ADD COLUMN IF NOT EXISTS avg_duration_minutes INTEGER DEFAULT 30;
ALTER TABLE public.specialties ADD COLUMN IF NOT EXISTS color TEXT DEFAULT '#3B82F6';

-- Table: stock_movements (1 columns)
ALTER TABLE public.stock_movements ADD COLUMN IF NOT EXISTS out_reason_type TEXT NULL;

-- Table: stripe_webhook_events (8 columns)
ALTER TABLE public.stripe_webhook_events ADD COLUMN IF NOT EXISTS alert_sent_at timestamptz;
ALTER TABLE public.stripe_webhook_events ADD COLUMN IF NOT EXISTS api_version text;
ALTER TABLE public.stripe_webhook_events ADD COLUMN IF NOT EXISTS attempts integer not null default 0;
ALTER TABLE public.stripe_webhook_events ADD COLUMN IF NOT EXISTS last_error text;
ALTER TABLE public.stripe_webhook_events ADD COLUMN IF NOT EXISTS livemode boolean not null default false;
ALTER TABLE public.stripe_webhook_events ADD COLUMN IF NOT EXISTS received_at timestamptz not null default now();
ALTER TABLE public.stripe_webhook_events ADD COLUMN IF NOT EXISTS status text not null default 'received';
ALTER TABLE public.stripe_webhook_events ADD COLUMN IF NOT EXISTS stripe_event_id text not null unique;

-- Table: subscriptions (1 columns)
ALTER TABLE public.subscriptions ADD COLUMN IF NOT EXISTS last_billing_event_at timestamptz;

-- Table: suppliers (2 columns)
ALTER TABLE public.suppliers ADD COLUMN IF NOT EXISTS document text;
ALTER TABLE public.suppliers ADD COLUMN IF NOT EXISTS notes text;

-- Table: support_messages (5 columns)
ALTER TABLE public.support_messages ADD COLUMN IF NOT EXISTS created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL;
ALTER TABLE public.support_messages ADD COLUMN IF NOT EXISTS message text NOT NULL;
ALTER TABLE public.support_messages ADD COLUMN IF NOT EXISTS metadata jsonb NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE public.support_messages ADD COLUMN IF NOT EXISTS sender text NOT NULL;
ALTER TABLE public.support_messages ADD COLUMN IF NOT EXISTS tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE;

-- Table: support_tickets (3 columns)
ALTER TABLE public.support_tickets ADD COLUMN IF NOT EXISTS channel text NOT NULL DEFAULT 'email';
ALTER TABLE public.support_tickets ADD COLUMN IF NOT EXISTS created_by uuid NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT;
ALTER TABLE public.support_tickets ADD COLUMN IF NOT EXISTS last_message_at timestamptz NOT NULL DEFAULT now();

-- Table: tenants (18 columns)
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS asaas_api_key text;
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS auto_queue_on_checkin BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS autonomous_config JSONB DEFAULT '{;
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS billing_cpf_cnpj text;
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS cashback_enabled boolean not null default false;
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS default_commission_percent DECIMAL(5,2) DEFAULT 10 CHECK (default_commission_percent >= 0 AND default_commission_percent <= 100);
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS email_reply_to TEXT;
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS gamification_enabled boolean DEFAULT true;
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS online_booking_enabled boolean not null default false;
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS patient_booking_enabled boolean NOT NULL DEFAULT false;
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS patient_payment_enabled boolean NOT NULL DEFAULT false;
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS points_enabled boolean        DEFAULT false;
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS retention_years INTEGER NOT NULL DEFAULT 20;
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS rnds_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS show_clinic_average_to_staff BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS smart_confirmation_enabled BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS sms_provider TEXT DEFAULT 'zenvia';
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS stone_api_key TEXT;

-- Table: tiss_guides (1 columns)
ALTER TABLE public.tiss_guides ADD COLUMN IF NOT EXISTS glosa_code TEXT;

-- Table: transcription_jobs (4 columns)
ALTER TABLE public.transcription_jobs ADD COLUMN IF NOT EXISTS error TEXT;
ALTER TABLE public.transcription_jobs ADD COLUMN IF NOT EXISTS job_name TEXT NOT NULL UNIQUE;
ALTER TABLE public.transcription_jobs ADD COLUMN IF NOT EXISTS s3_uri TEXT NOT NULL;
ALTER TABLE public.transcription_jobs ADD COLUMN IF NOT EXISTS transcript TEXT;

-- Table: treatment_plan_items (10 columns)
ALTER TABLE public.treatment_plan_items ADD COLUMN IF NOT EXISTS appointment_id UUID REFERENCES public.appointments(id) ON DELETE SET NULL;
ALTER TABLE public.treatment_plan_items ADD COLUMN IF NOT EXISTS completed_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL;
ALTER TABLE public.treatment_plan_items ADD COLUMN IF NOT EXISTS discount_percent DECIMAL(5,2) DEFAULT 0;
ALTER TABLE public.treatment_plan_items ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.treatment_plan_items ADD COLUMN IF NOT EXISTS odontogram_tooth_id UUID REFERENCES public.odontogram_teeth(id) ON DELETE SET NULL;
ALTER TABLE public.treatment_plan_items ADD COLUMN IF NOT EXISTS procedure_category TEXT;
ALTER TABLE public.treatment_plan_items ADD COLUMN IF NOT EXISTS quantity INTEGER NOT NULL DEFAULT 1;
ALTER TABLE public.treatment_plan_items ADD COLUMN IF NOT EXISTS region TEXT;
ALTER TABLE public.treatment_plan_items ADD COLUMN IF NOT EXISTS total_price DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE public.treatment_plan_items ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- Table: treatment_plans (10 columns)
ALTER TABLE public.treatment_plans ADD COLUMN IF NOT EXISTS approved_by_client BOOLEAN DEFAULT FALSE;
ALTER TABLE public.treatment_plans ADD COLUMN IF NOT EXISTS client_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.treatment_plans ADD COLUMN IF NOT EXISTS client_signature TEXT;
ALTER TABLE public.treatment_plans ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE public.treatment_plans ADD COLUMN IF NOT EXISTS discount_percent DECIMAL(5,2) DEFAULT 0;
ALTER TABLE public.treatment_plans ADD COLUMN IF NOT EXISTS discount_value DECIMAL(12,2) DEFAULT 0;
ALTER TABLE public.treatment_plans ADD COLUMN IF NOT EXISTS final_value DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE public.treatment_plans ADD COLUMN IF NOT EXISTS installments INTEGER DEFAULT 1;
ALTER TABLE public.treatment_plans ADD COLUMN IF NOT EXISTS odontogram_id UUID REFERENCES public.odontograms(id) ON DELETE SET NULL;
ALTER TABLE public.treatment_plans ADD COLUMN IF NOT EXISTS signature_ip TEXT;

-- Table: triage_records (17 columns)
ALTER TABLE public.triage_records ADD COLUMN IF NOT EXISTS allergies TEXT;
ALTER TABLE public.triage_records ADD COLUMN IF NOT EXISTS appointment_id UUID REFERENCES public.appointments(id) ON DELETE SET NULL;
ALTER TABLE public.triage_records ADD COLUMN IF NOT EXISTS blood_pressure_diastolic INTEGER;
ALTER TABLE public.triage_records ADD COLUMN IF NOT EXISTS blood_pressure_systolic INTEGER;
ALTER TABLE public.triage_records ADD COLUMN IF NOT EXISTS client_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.triage_records ADD COLUMN IF NOT EXISTS current_medications TEXT;
ALTER TABLE public.triage_records ADD COLUMN IF NOT EXISTS heart_rate INTEGER;
ALTER TABLE public.triage_records ADD COLUMN IF NOT EXISTS height_cm INTEGER;
ALTER TABLE public.triage_records ADD COLUMN IF NOT EXISTS medical_history TEXT;
ALTER TABLE public.triage_records ADD COLUMN IF NOT EXISTS oxygen_saturation NUMERIC(5,1);
ALTER TABLE public.triage_records ADD COLUMN IF NOT EXISTS pain_scale INTEGER CHECK (pain_scale BETWEEN 0 AND 10);
ALTER TABLE public.triage_records ADD COLUMN IF NOT EXISTS performed_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL;
ALTER TABLE public.triage_records ADD COLUMN IF NOT EXISTS respiratory_rate INTEGER;
ALTER TABLE public.triage_records ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'pendente';
ALTER TABLE public.triage_records ADD COLUMN IF NOT EXISTS temperature NUMERIC(4,1);
ALTER TABLE public.triage_records ADD COLUMN IF NOT EXISTS triaged_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.triage_records ADD COLUMN IF NOT EXISTS weight_kg NUMERIC(5,1);

-- Table: user_notification_preferences (9 columns)
ALTER TABLE public.user_notification_preferences ADD COLUMN IF NOT EXISTS appointment_cancelled BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE public.user_notification_preferences ADD COLUMN IF NOT EXISTS appointment_completed BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE public.user_notification_preferences ADD COLUMN IF NOT EXISTS appointment_created BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE public.user_notification_preferences ADD COLUMN IF NOT EXISTS commission_generated BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE public.user_notification_preferences ADD COLUMN IF NOT EXISTS commission_paid BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE public.user_notification_preferences ADD COLUMN IF NOT EXISTS goal_approved BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE public.user_notification_preferences ADD COLUMN IF NOT EXISTS goal_reached BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE public.user_notification_preferences ADD COLUMN IF NOT EXISTS goal_rejected BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE public.user_notification_preferences ADD COLUMN IF NOT EXISTS goal_reminder BOOLEAN NOT NULL DEFAULT true;

-- Table: user_tour_progress (3 columns)
ALTER TABLE public.user_tour_progress ADD COLUMN IF NOT EXISTS step_index integer NOT NULL DEFAULT 0;
ALTER TABLE public.user_tour_progress ADD COLUMN IF NOT EXISTS tour_key text NOT NULL;
ALTER TABLE public.user_tour_progress ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

-- Table: voucher_redemptions (3 columns)
ALTER TABLE public.voucher_redemptions ADD COLUMN IF NOT EXISTS order_id uuid        REFERENCES orders(id)             ON DELETE SET NULL;
ALTER TABLE public.voucher_redemptions ADD COLUMN IF NOT EXISTS redeemed_at timestamptz DEFAULT now();
ALTER TABLE public.voucher_redemptions ADD COLUMN IF NOT EXISTS redeemed_by uuid        REFERENCES profiles(id)           ON DELETE SET NULL;

-- Table: vouchers (6 columns)
ALTER TABLE public.vouchers ADD COLUMN IF NOT EXISTS created_by uuid        REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.vouchers ADD COLUMN IF NOT EXISTS expires_at timestamptz;
ALTER TABLE public.vouchers ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.vouchers ADD COLUMN IF NOT EXISTS service_id uuid        REFERENCES public.procedures(id) ON DELETE SET NULL;
ALTER TABLE public.vouchers ADD COLUMN IF NOT EXISTS status text        NOT NULL DEFAULT 'ativo'
                 CHECK (status IN ('ativo','resgatado','expirado'));
ALTER TABLE public.vouchers ADD COLUMN IF NOT EXISTS valor numeric(10,2) NOT NULL DEFAULT 0;

-- Table: waitlist (7 columns)
ALTER TABLE public.waitlist ADD COLUMN IF NOT EXISTS client_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.waitlist ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;
ALTER TABLE public.waitlist ADD COLUMN IF NOT EXISTS preferred_periods TEXT[];
ALTER TABLE public.waitlist ADD COLUMN IF NOT EXISTS reason TEXT;
ALTER TABLE public.waitlist ADD COLUMN IF NOT EXISTS scheduled_at TIMESTAMPTZ;
ALTER TABLE public.waitlist ADD COLUMN IF NOT EXISTS service_id UUID REFERENCES public.procedures(id) ON DELETE SET NULL;
ALTER TABLE public.waitlist ADD COLUMN IF NOT EXISTS specialty_id UUID REFERENCES public.specialties(id) ON DELETE SET NULL;

COMMIT;

-- Summary: 1 missing tables, 696 missing columns across 125 tables